# Generated by Django 4.1.6 on 2024-10-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specific_id",
                    models.CharField(max_length=255, verbose_name="Specific Id"),
                ),
                (
                    "issn",
                    models.CharField(max_length=255, null=True, verbose_name="DOI"),
                ),
                (
                    "title",
                    models.CharField(max_length=1024, null=True, verbose_name="Título"),
                ),
                (
                    "updated",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Source updated date"
                    ),
                ),
                (
                    "created",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Source created date"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Arquivo JSON"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.source",
                        verbose_name="Origem",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sourcejournal",
            index=models.Index(fields=["issn"], name="journal_sou_issn_b43f7e_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcejournal",
            index=models.Index(
                fields=["specific_id"], name="journal_sou_specifi_206501_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcejournal",
            index=models.Index(fields=["title"], name="journal_sou_title_cd0c69_idx"),
        ),
    ]
