# Generated by Django 4.1.6 on 2024-10-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sourcejournal",
            name="journal_sou_issn_b43f7e_idx",
        ),
        migrations.RemoveField(
            model_name="sourcejournal",
            name="issn",
        ),
        migrations.AddField(
            model_name="sourcejournal",
            name="country_code",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Country Code"
            ),
        ),
        migrations.AddField(
            model_name="sourcejournal",
            name="issn_l",
            field=models.CharField(max_length=255, null=True, verbose_name="ISSN_L"),
        ),
        migrations.AddField(
            model_name="sourcejournal",
            name="issns",
            field=models.CharField(max_length=255, null=True, verbose_name="ISSN"),
        ),
        migrations.AddIndex(
            model_name="sourcejournal",
            index=models.Index(fields=["issns"], name="journal_sou_issns_971d00_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcejournal",
            index=models.Index(fields=["issn_l"], name="journal_sou_issn_l_971c0c_idx"),
        ),
    ]
