# Generated by Django 3.2.12 on 2022-08-29 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="region",
        ),
    ]
