# Generated by Django 3.2.12 on 2022-08-15 12:26

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('location', '0005_location_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='institution',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='institution.institution'),
        ),
    ]
