# Generated by Django 3.2.12 on 2022-08-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='institution',
        ),
    ]
