# Generated by Django 3.2.12 on 2022-08-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20220815_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Locations'},
        ),
    ]
