# Generated by Django 3.2.12 on 2022-08-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=510, null=True, verbose_name='Nome de afiliação')),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('given', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome dado')),
                ('orcid', models.CharField(blank=True, max_length=255, null=True, verbose_name='ORCID')),
                ('authenticated_orcid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Autenticado')),
                ('affiliation', models.ForeignKey(blank=True, max_length=510, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarly_articles.affiliations')),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_issn_l', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISSN-L')),
                ('journal_issns', models.CharField(blank=True, max_length=255, null=True, verbose_name="ISSN's")),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do periódico')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publicador')),
                ('journal_is_in_doaj', models.BooleanField(blank=True, default=False, max_length=255, null=True, verbose_name='DOAJ')),
            ],
        ),
        migrations.CreateModel(
            name='RawUnpaywall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=255, verbose_name='DOI')),
                ('harvesting_creation', models.CharField(max_length=255, verbose_name='Data da coleta')),
                ('is_paratext', models.BooleanField(blank=True, default=False, null=True, verbose_name='Paratext')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ano')),
                ('resource_type', models.CharField(blank=True, choices=[('', ''), ('book-section', 'Book Section'), ('monograph', 'Monograph'), ('report', 'Report'), ('peer-review', 'Peer Review'), ('book-track', 'Book Track'), ('journal-article', 'Journal Article'), ('book-part', 'Part'), ('other', 'Other'), ('book', 'Book'), ('journal-volume', 'Journal Volume'), ('book-set', 'Book Set'), ('reference-entry', 'Reference Entry'), ('proceedings-article', 'Proceedings Article'), ('journal', 'Journal'), ('component', 'Component'), ('book-chapter', 'Book Chapter'), ('proceedings-series', 'Proceedings Series'), ('report-series', 'Report Series'), ('proceedings', 'Proceedings'), ('standard', 'Standard'), ('reference-book', 'Reference Book'), ('posted-content', 'Posted Content'), ('journal-issue', 'Journal Issue'), ('dissertation', 'Dissertation'), ('grant', 'Grant'), ('dataset', 'Dataset'), ('book-series', 'Book Series'), ('edited-book', 'Edited Book'), ('standard-series', 'Standard Series')], max_length=255, verbose_name='Tipo de recurso')),
                ('update', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atualiza')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='Arquivo JSON')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarlyArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, verbose_name='DOI')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano')),
                ('contributors', models.ManyToManyField(blank=True, null=True, to='scholarly_articles.Contributors')),
                ('journal', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarly_articles.journals')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de erro')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensagem de erro')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='errorlog_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('document_id', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarly_articles.scholarlyarticles')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errorlog_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
