# Generated by Django 3.2.12 on 2022-09-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawunpaywall',
            index=models.Index(fields=['doi'], name='scholarly_a_doi_e75c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawunpaywall',
            index=models.Index(fields=['year'], name='scholarly_a_year_c2349f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawunpaywall',
            index=models.Index(fields=['resource_type'], name='scholarly_a_resourc_0d5bcb_idx'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='apc',
            field=models.CharField(blank=True, choices=[('', ''), ('YES', 'YES'), ('NO', 'NO')], max_length=25, null=True, verbose_name='Article Processing Charge'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='qualification',
            field=models.CharField(blank=True, choices=[('', ''), ('Gold', 'gold'), ('Hybrid', 'hybrid'), ('Bronze', 'bronze'), ('Green', 'green'), ('Closed', 'closed')], max_length=25, null=True, verbose_name='Open Access Qualification'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='source',
            field=models.CharField(blank=True, choices=[('', ''), ('UNPAYWALL', 'UNPAYWALL')], max_length=255, null=True, verbose_name='Record Source'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='use_license',
            field=models.CharField(blank=True, choices=[('', ''), ('CC0', 'CC0'), ('CC-BY', 'CC-BY'), ('CC-BYNC', 'CC-BYNC'), ('CC-BYND', 'CC-BYND'), ('CC-BYNCND', 'CC-BYNCND')], max_length=25, null=True, verbose_name='Use License'),
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to='scholarly_articles.Contributors', verbose_name='Contribuidores'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='journal',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarly_articles.journals', verbose_name='Periódico'),
        ),
    ]
