# Generated by Django 3.2.12 on 2022-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0002_auto_20220906_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarlyarticles',
            name='qualification',
        ),
        migrations.AddField(
            model_name='scholarlyarticles',
            name='open_access_status',
            field=models.CharField(blank=True, choices=[('', ''), ('gold', 'Gold'), ('hybrid', 'Hybrid'), ('bronze', 'Bronze'), ('green', 'Green'), ('closed', 'Closed')], max_length=25, null=True, verbose_name='Open Access Status'),
        ),
    ]
