# Generated by Django 3.2.12 on 2022-10-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_institution_institution_type'),
        ('scholarly_articles', '0004_auto_20221015_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=510, null=True, verbose_name='Nome de afiliação')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Affiliation Source')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('given', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome dado')),
                ('orcid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID')),
                ('authenticated_orcid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Autenticado')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_issn_l', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISSN-L')),
                ('journal_issns', models.CharField(blank=True, max_length=50, null=True, verbose_name="ISSN's")),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do periódico')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publicador')),
                ('journal_is_in_doaj', models.BooleanField(blank=True, default=False, null=True, verbose_name='DOAJ')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarlyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Título')),
                ('volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Volume')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano')),
                ('open_access_status', models.CharField(blank=True, choices=[('', ''), ('gold', 'Gold'), ('hybrid', 'Hybrid'), ('bronze', 'Bronze'), ('green', 'Green'), ('closed', 'Closed')], max_length=50, null=True, verbose_name='Open Access Status')),
                ('use_license', models.CharField(blank=True, choices=[('', ''), ('CC0', 'CC0'), ('CC-BY', 'CC-BY'), ('CC-BYNC', 'CC-BYNC'), ('CC-BYND', 'CC-BYND'), ('CC-BYNCND', 'CC-BYNCND')], max_length=50, null=True, verbose_name='Use License')),
                ('apc', models.CharField(blank=True, choices=[('', ''), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True, verbose_name='Article Processing Charge')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Record Source')),
                ('contributors', models.ManyToManyField(blank=True, to='scholarly_articles.Contributor', verbose_name='Contributor')),
                ('journal', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarly_articles.journal', verbose_name='Periódico')),
            ],
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='scholarlyarticles',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='scholarlyarticles',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Affiliations',
        ),
        migrations.DeleteModel(
            name='Contributors',
        ),
        migrations.DeleteModel(
            name='Journals',
        ),
        migrations.DeleteModel(
            name='ScholarlyArticles',
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_issn_l'], name='scholarly_a_journal_d59659_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_issns'], name='scholarly_a_journal_8b491f_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_name'], name='scholarly_a_journal_a5d1e7_idx'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='affiliation',
            field=models.ManyToManyField(blank=True, to='scholarly_articles.Affiliation'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='official',
            field=models.ForeignKey(blank=True, max_length=1020, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Official Affiliation Name'),
        ),
        migrations.AddIndex(
            model_name='scholarlyarticle',
            index=models.Index(fields=['doi'], name='scholarly_a_doi_b922f8_idx'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['family'], name='scholarly_a_family_fa6d95_idx'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['given'], name='scholarly_a_given_ddd259_idx'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['orcid'], name='scholarly_a_orcid_61f31d_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliation',
            index=models.Index(fields=['name'], name='scholarly_a_name_4f21bf_idx'),
        ),
    ]
