# Generated by Django 3.2.12 on 2022-09-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0004_affiliations_official'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='affiliations',
            index=models.Index(fields=['name'], name='scholarly_a_name_565309_idx'),
        ),
        migrations.AddIndex(
            model_name='contributors',
            index=models.Index(fields=['family'], name='scholarly_a_family_741f92_idx'),
        ),
        migrations.AddIndex(
            model_name='contributors',
            index=models.Index(fields=['given'], name='scholarly_a_given_cab90c_idx'),
        ),
        migrations.AddIndex(
            model_name='contributors',
            index=models.Index(fields=['orcid'], name='scholarly_a_orcid_2fe794_idx'),
        ),
        migrations.AddIndex(
            model_name='contributors',
            index=models.Index(fields=['affiliation'], name='scholarly_a_affilia_cab862_idx'),
        ),
        migrations.AddIndex(
            model_name='journals',
            index=models.Index(fields=['journal_issn_l'], name='scholarly_a_journal_23ada4_idx'),
        ),
        migrations.AddIndex(
            model_name='journals',
            index=models.Index(fields=['journal_issns'], name='scholarly_a_journal_82745c_idx'),
        ),
        migrations.AddIndex(
            model_name='journals',
            index=models.Index(fields=['journal_name'], name='scholarly_a_journal_b95c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarlyarticles',
            index=models.Index(fields=['doi'], name='scholarly_a_doi_967c29_idx'),
        ),
    ]
