# Generated by Django 3.2.12 on 2022-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0005_remove_affiliations_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawunpaywall',
            index=models.Index(fields=['is_paratext'], name='scholarly_a_is_para_720cbd_idx'),
        ),
    ]
