# Generated by Django 3.2.12 on 2022-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0005_auto_20221016_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Journal Source'),
        ),
    ]
