# Generated by Django 3.2.12 on 2022-09-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0005_auto_20220912_1448'),
        ('scholarly_articles', '0005_errorlog_error_line'),
    ]

    operations = [
    ]
