# Generated by Django 3.2.12 on 2022-10-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholarly_articles", "0006_rawunpaywall_scholarly_a_is_para_720cbd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliations",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Country"
            ),
        ),
    ]
