# Generated by Django 3.2.12 on 2022-09-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0006_merge_20220914_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='scholarly_articles.Contributors', verbose_name='Contribuidores'),
        ),
    ]
