# Generated by Django 3.2.12 on 2022-10-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0006_journal_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem'),
        ),
    ]
