# Generated by Django 3.2.12 on 2022-10-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0007_auto_20221016_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem')),
            ],
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='source',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='source',
        ),
        migrations.RemoveField(
            model_name='scholarlyarticle',
            name='source',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='source',
            field=models.ManyToManyField(blank=True, to='scholarly_articles.Source', verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='source',
            field=models.ManyToManyField(blank=True, to='scholarly_articles.Source', verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='journal',
            name='source',
            field=models.ManyToManyField(blank=True, to='scholarly_articles.Source', verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='scholarlyarticle',
            name='source',
            field=models.ManyToManyField(blank=True, to='scholarly_articles.Source', verbose_name='Record Source'),
        ),
    ]
