# Generated by Django 3.2.12 on 2022-09-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0007_alter_scholarlyarticles_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='document_id',
        ),
    ]
