# Generated by Django 3.2.12 on 2022-10-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0008_auto_20221019_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='source',
            new_name='sources',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='source',
            new_name='sources',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='source',
            new_name='sources',
        ),
        migrations.RenameField(
            model_name='scholarlyarticle',
            old_name='source',
            new_name='sources',
        ),
    ]
