# Generated by Django 3.2.12 on 2022-11-08 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scholarly_articles", "0007_auto_20221022_2117"),
        ("scholarly_articles", "0008_alter_affiliations_country"),
    ]

    operations = []
