# Generated by Django 3.2.12 on 2022-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0009_auto_20220921_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='apc',
            field=models.CharField(blank=True, choices=[('', ''), ('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True, verbose_name='Article Processing Charge'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='open_access_status',
            field=models.CharField(blank=True, choices=[('', ''), ('gold', 'Gold'), ('hybrid', 'Hybrid'), ('bronze', 'Bronze'), ('green', 'Green'), ('closed', 'Closed')], max_length=255, null=True, verbose_name='Open Access Status'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='use_license',
            field=models.CharField(blank=True, choices=[('', ''), ('CC0', 'CC0'), ('CC-BY', 'CC-BY'), ('CC-BYNC', 'CC-BYNC'), ('CC-BYND', 'CC-BYND'), ('CC-BYNCND', 'CC-BYNCND')], max_length=255, null=True, verbose_name='Use License'),
        ),
    ]
