# Generated by Django 3.2.12 on 2022-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0010_auto_20221028_1327'),
        ('institution', '0004_institution_source'),
        ('scholarly_articles', '0009_merge_20221103_1413'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journals',
            name='scholarly_a_publish_e147df_idx',
        ),
        migrations.AddField(
            model_name='journals',
            name='thematic_areas',
            field=models.ManyToManyField(blank=True, to='usefulmodels.ThematicArea', verbose_name='Área temática'),
        ),
        migrations.RemoveField(
            model_name='journals',
            name='publisher',
        ),
        migrations.AddField(
            model_name='journals',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='institution.Institution', verbose_name='Publicador'),
        ),
    ]
