# Generated by Django 4.1.6 on 2023-04-05 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scholarly_articles", "0010_auto_20221121_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of license, it is not required",
                        max_length=100,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "delay_in_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days between the publication date of the work and the start date of this license",
                        null=True,
                        verbose_name="Delay in Days",
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        help_text="Date on which this license begins to take effect",
                        max_length=100,
                        null=True,
                        verbose_name="Stard Date",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link to a web page describing this license",
                        verbose_name="URL",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="rawunpaywall",
            name="update",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Atualizar"
            ),
        ),
        migrations.AlterField(
            model_name="scholarlyarticles",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNPAYWALL", "UNPAYWALL"),
                    ("CROSSREF", "CROSSREF"),
                ],
                max_length=50,
                null=True,
                verbose_name="Record Source",
            ),
        ),
    ]
