# Generated by Django 3.2.12 on 2022-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0010_auto_20220921_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_is_in_doaj',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='DOAJ'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_issn_l',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISSN-L'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_issns',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="ISSN's"),
        ),
        migrations.AlterField(
            model_name='rawunpaywall',
            name='doi',
            field=models.CharField(max_length=50, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='rawunpaywall',
            name='harvesting_creation',
            field=models.CharField(max_length=20, verbose_name='Data da coleta'),
        ),
        migrations.AlterField(
            model_name='rawunpaywall',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('', ''), ('book-section', 'Book Section'), ('monograph', 'Monograph'), ('report', 'Report'), ('peer-review', 'Peer Review'), ('book-track', 'Book Track'), ('journal-article', 'Journal Article'), ('book-part', 'Part'), ('other', 'Other'), ('book', 'Book'), ('journal-volume', 'Journal Volume'), ('book-set', 'Book Set'), ('reference-entry', 'Reference Entry'), ('proceedings-article', 'Proceedings Article'), ('journal', 'Journal'), ('component', 'Component'), ('book-chapter', 'Book Chapter'), ('proceedings-series', 'Proceedings Series'), ('report-series', 'Report Series'), ('proceedings', 'Proceedings'), ('standard', 'Standard'), ('reference-book', 'Reference Book'), ('posted-content', 'Posted Content'), ('journal-issue', 'Journal Issue'), ('dissertation', 'Dissertation'), ('grant', 'Grant'), ('dataset', 'Dataset'), ('book-series', 'Book Series'), ('edited-book', 'Edited Book'), ('standard-series', 'Standard Series')], max_length=50, verbose_name='Tipo de recurso'),
        ),
        migrations.AlterField(
            model_name='rawunpaywall',
            name='update',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Atualiza'),
        ),
        migrations.AlterField(
            model_name='rawunpaywall',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='apc',
            field=models.CharField(blank=True, choices=[('', ''), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True, verbose_name='Article Processing Charge'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='open_access_status',
            field=models.CharField(blank=True, choices=[('', ''), ('gold', 'Gold'), ('hybrid', 'Hybrid'), ('bronze', 'Bronze'), ('green', 'Green'), ('closed', 'Closed')], max_length=50, null=True, verbose_name='Open Access Status'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='source',
            field=models.CharField(blank=True, choices=[('', ''), ('UNPAYWALL', 'UNPAYWALL')], max_length=50, null=True, verbose_name='Record Source'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='use_license',
            field=models.CharField(blank=True, choices=[('', ''), ('CC0', 'CC0'), ('CC-BY', 'CC-BY'), ('CC-BYNC', 'CC-BYNC'), ('CC-BYND', 'CC-BYND'), ('CC-BYNCND', 'CC-BYNCND')], max_length=50, null=True, verbose_name='Use License'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano'),
        ),
    ]
