# Generated by Django 4.1.6 on 2023-04-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0011_license_alter_errorlog_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarlyarticles",
            name="license",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scholarly_articles.license",
                verbose_name="License",
            ),
        ),
    ]
