# Generated by Django 4.1.6 on 2023-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0012_scholarlyarticles_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarlyarticles",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNPAYWALL", "UNPAYWALL"),
                    ("CROSSREF", "CROSSREF"),
                    ("CAPES", "CAPES"),
                ],
                max_length=50,
                null=True,
                verbose_name="Record Source",
            ),
        ),
    ]
