# Generated by Django 3.2.12 on 2022-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0012_alter_rawunpaywall_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarlyarticles',
            name='title',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Título'),
        ),
    ]
