# Generated by Django 4.1.6 on 2023-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0013_alter_scholarlyarticles_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarlyarticles",
            name="id_int_production",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Id Intellectual Production",
            ),
        ),
        migrations.AlterField(
            model_name="scholarlyarticles",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNPAYWALL", "UNPAYWALL"),
                    ("CROSSREF", "CROSSREF"),
                    ("SUCUPIRA", "SUCUPIRA"),
                ],
                max_length=50,
                null=True,
                verbose_name="Record Source",
            ),
        ),
    ]
