# Generated by Django 4.1.6 on 2023-06-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_creator_and_more"),
        ("scholarly_articles", "0014_scholarlyarticles_id_int_production_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Program Name",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        max_length=1020,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="institution.institution",
                        verbose_name="Instituição",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contributors",
            name="programs",
            field=models.ManyToManyField(
                blank=True, to="scholarly_articles.programs", verbose_name="Programs"
            ),
        ),
    ]
