# Generated by Django 4.1.6 on 2023-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0015_programs_contributors_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorlog",
            name="error_type",
            field=models.CharField(
                blank=True,
                help_text="Type of python error.",
                max_length=100,
                null=True,
                verbose_name="Tipo de erro",
            ),
        ),
    ]
