# Generated by Django 4.1.6 on 2023-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0016_alter_errorlog_error_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorlog",
            name="data_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference to the data, can be id, line. Use line:10 or id:452 to to differ between id|line.",
                max_length=100,
                null=True,
                verbose_name="Reference data",
            ),
        ),
    ]
