# Generated by Django 4.1.6 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0017_alter_errorlog_data_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorlog",
            name="data",
            field=models.TextField(
                blank=True,
                help_text="Data when the error happened.",
                null=True,
                verbose_name="Data",
            ),
        ),
    ]
