# Generated by Django 4.1.6 on 2023-06-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0018_alter_errorlog_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journals",
            name="journal_name",
            field=models.CharField(
                blank=True, max_length=510, null=True, verbose_name="Nome do periódico"
            ),
        ),
        migrations.AlterField(
            model_name="scholarlyarticles",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scholarly_articles.journals",
                verbose_name="Periódico",
            ),
        ),
    ]
