# Generated by Django 4.1.6 on 2023-06-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0019_alter_journals_journal_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarlyarticles",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scholarly_articles.license",
                verbose_name="License",
            ),
        ),
    ]
