# Generated by Django 4.1.6 on 2023-06-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scholarly_articles", "0020_alter_scholarlyarticles_license"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Program Name",
                    ),
                ),
                (
                    "affiliation",
                    models.ForeignKey(
                        blank=True,
                        max_length=1020,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scholarly_articles.affiliations",
                        verbose_name="Afiliações",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Programs",
        ),
        migrations.AlterField(
            model_name="contributors",
            name="programs",
            field=models.ManyToManyField(
                blank=True, to="scholarly_articles.program", verbose_name="Program"
            ),
        ),
    ]
