# Generated by Django 3.2.12 on 2022-08-08 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usefulmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='city',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='city_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
        migrations.AlterField(
            model_name='country',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acrônimo do país'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='country',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='country_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do País'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
        migrations.AlterField(
            model_name='state',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acrônimo do estado'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='state',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='state_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do estado'),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
    ]
