# Generated by Django 3.2.12 on 2022-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0002_auto_20220808_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of the city'),
        ),
        migrations.AlterField(
            model_name='country',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acronym to the Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of the Country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acronym to the state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of the state'),
        ),
    ]
