# Generated by Django 3.2.12 on 2022-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0003_auto_20220809_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='country',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acrônimo do país'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do País'),
        ),
        migrations.AlterField(
            model_name='state',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acrônimo do estado'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do estado'),
        ),
    ]
