# Generated by Django 3.2.12 on 2022-09-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0003_auto_20220907_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Países'},
        ),
    ]
