# Generated by Django 3.2.12 on 2022-08-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0004_auto_20220815_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='country',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acrônimo do país'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do País'),
        ),
        migrations.AlterField(
            model_name='state',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acrônimo do estado'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do estado'),
        ),
    ]
