# Generated by Django 3.2.12 on 2022-10-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usefulmodels", "0004_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("Norte", "Norte"),
                    ("Nordeste", "Nordeste"),
                    ("Centro-oeste", "Centro-Oeste"),
                    ("Sudeste", "Sudeste"),
                    ("Sul", "Sul"),
                    ("ALL", "ALL"),
                    ("NOT APPLICABLE", "NOT_APPLICABLE"),
                    ("UNDEFINED", "UNDEFINED"),
                ],
                max_length=255,
                null=True,
                verbose_name="Região",
            ),
        ),
    ]
