# Generated by Django 3.2.12 on 2022-08-17 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usefulmodels', '0005_auto_20220815_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('level0', models.CharField(blank=True, choices=[('', ''), ('Ciências da Vida', 'Ciências da Vida'), ('Ciências Físicas, Tecnológicas e Multidisciplinares', 'Ciências Físicas, Tecnológicas e Multidisciplinares'), ('humanidades', 'Humanidades')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 0')),
                ('level1', models.CharField(blank=True, choices=[('', ''), ('Ciências Agrárias', 'Ciências Agrárias'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Ciências da Saúde', 'Ciências da Saúde'), ('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra'), ('Ciências Humanas', 'Ciências Humanas'), ('Ciências Sociais Aplicadas', 'Ciências Sociais Aplicadas'), ('Engenharias', 'Engenharias'), ('Lingüística, Letras e Artes', 'Lingüística, Letras e Artes')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 1')),
                ('level2', models.CharField(blank=True, choices=[('', ''), ('Ciências Agrárias', 'Ciências Agrárias'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Ciências da Saúde', 'Ciências da Saúde'), ('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra'), ('Ciências Humanas', 'Ciências Humanas'), ('Ciências Sociais Aplicadas', 'Ciências Sociais Aplicadas'), ('Engenharias', 'Engenharias'), ('Lingüística, Letras e Artes', 'Lingüística, Letras e Artes')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 2')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='thematicarea_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematicarea_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
