# Generated by Django 3.2.12 on 2022-08-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0007_alter_thematicarea_level2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thematicarea',
            options={'verbose_name': 'Thematic Area', 'verbose_name_plural': 'Thematic areas'},
        ),
    ]
