# Generated by Django 3.2.12 on 2022-10-28 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usefulmodels", "0009_country_capital"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="acronym2",
            new_name="acron2",
        ),
        migrations.RenameField(
            model_name="country",
            old_name="acronym",
            new_name="acron3",
        ),
    ]
