# Generated by Django 3.2.12 on 2022-08-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0009_auto_20220817_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
