# Generated by Django 3.2.12 on 2022-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0011_action_pratice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AlterModelOptions(
            name='pratice',
            options={'verbose_name': 'Pratice', 'verbose_name_plural': 'Pratices'},
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='level2',
            field=models.CharField(blank=True, choices=[('', ''), ('Ciência de Alimentos', 'Ciência de Alimentos'), ('Ciências Agrárias I', 'Ciências Agrárias I'), ('Medicina Veterinária', 'Medicina Veterinária'), ('Zootecnia/Recursos Pesqueiros', 'Zootecnia/Recursos Pesqueiros'), ('Biodiversidade', 'Biodiversidade'), ('Ciências Biológicas I', 'Ciências Biológicas I'), ('Ciências Biológicas II', 'Ciências Biológicas II'), ('Ciências Biológicas III', 'Ciências Biológicas III'), ('Educação Física', 'Educação Física'), ('Enfermagem', 'Enfermagem'), ('Farmácia', 'Farmácia'), ('Medicina I', 'Medicina I'), ('Medicina II', 'Medicina II'), ('Medicina III', 'Medicina III'), ('Nutrição', 'Nutrição'), ('Odontologia', 'Odontologia'), ('Saúde Coletiva', 'Saúde Coletiva'), ('Astronomia/Física', 'Astronomia/Física'), ('Ciências da Computação', 'Ciências da Computação'), ('Geociências', 'Geociências'), ('Matemática/Probabilidade Estatística', 'Matemática/Probabilidade Estatística'), ('Química', 'Química'), ('Antropologia/Arqueologia', 'Antropologia/Arqueologia'), ('Ciência Política e Relações Internacionais', 'Ciência Política e Relações Internacionais'), ('Ciências da Religião e Teologia', 'Ciências da Religião e Teologia'), ('Educação', 'Educação'), ('Filosofia', 'Filosofia'), ('Geografia', 'Geografia'), ('História', 'História'), ('Psicologia', 'Psicologia'), ('Sociologia', 'Sociologia'), ('Turismo', 'Turismo'), ('Arquitetura, Urbanismo e Design', 'Arquitetura, Urbanismo e Design'), ('Comunicação e Informação', 'Comunicação e Informação'), ('Direito', 'Direito'), ('Economia', 'Economia'), ('Planejamento Urbano e Regional/Demografia', 'Planejamento Urbano e Regional/Demografia'), ('Serviço Social', 'Serviço Social'), ('Engenharias', 'Engenharias'), ('Engenharias I', 'Engenharias I'), ('Engenharias II', 'Engenharias II'), ('Engenharias III', 'Engenharias III'), ('Engenharias IV', 'Engenharias IV'), ('Artes', 'Artes'), ('Linguística e Literatura', 'Linguística e Literatura')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 2'),
        ),
    ]
