# Generated by Django 4.1.6 on 2026-01-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practice",
            options={"verbose_name": "Prática", "verbose_name_plural": "Práticas"},
        ),
        migrations.AlterField(
            model_name="actionandpractice",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.practice",
                verbose_name="Prática",
            ),
        ),
    ]
