# Generated by Django 5.2.10 on 2026-02-20 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usefulmodels", "0013_alter_practice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"verbose_name": "Localização", "verbose_name_plural": "Ações"},
        ),
        migrations.AlterField(
            model_name="actionandpractice",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.action",
                verbose_name="Localização",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level0",
            field=models.CharField(
                blank=True,
                help_text="Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                max_length=255,
                null=True,
                verbose_name="Nível 0",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level1",
            field=models.CharField(
                blank=True,
                help_text="Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao",
                max_length=255,
                null=True,
                verbose_name="Nível 1",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level2",
            field=models.CharField(
                blank=True,
                help_text="Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao",
                max_length=255,
                null=True,
                verbose_name="Nível 2",
            ),
        ),
    ]
