# Generated by Django 3.2.12 on 2022-08-25 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0014_remove_infrastructuredirectory_pratice'),
        ('policy_directory', '0010_remove_policydirectory_pratice'),
        ('education_directory', '0013_remove_educationdirectory_pratice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_directory', '0010_remove_eventdirectory_pratice'),
        ('usefulmodels', '0013_auto_20220822_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the pratice')),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Code of the pratice')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='practice_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
        migrations.DeleteModel(
            name='Pratice',
        ),
    ]
