TYPE_OF_RESOURCE = [
    ("", ""),
    ("Book Section", "book-section"),
    ("Monograph", "monograph"),
    ("Report", "report"),
    ("Peer Review", "peer-review"),
    ("Book Track", "book-track"),
    ("Journal Article", "journal-article"),
    ("Part", "book-part"),
    ("Other", "other"),
    ("Book", "book"),
    ("Journal Volume", "journal-volume"),
    ("Book Set", "book-set"),
    ("Reference Entry", "reference-entry"),
    ("Proceedings Article", "proceedings-article"),
    ("Journal", "journal"),
    ("Component", "component"),
    ("Book Chapter", "book-chapter"),
    ("Proceedings Series", "proceedings-series"),
    ("Report Series", "report-series"),
    ("Proceedings", "proceedings"),
    ("Standard", "standard"),
    ("Reference Book", "reference-book"),
    ("Posted Content", "posted-content"),
    ("Journal Issue", "journal-issue"),
    ("Dissertation", "dissertation"),
    ("Grant", "grant"),
    ("Dataset", "dataset"),
    ("Book Series", "book-series"),
    ("Edited Book", "edited-book"),
    ("Standard Series", "standard-series")
]
