from django.utils.translation import gettext as _

translates = {
    "education_directory": _("Dados de educação"),
    "event_directory": _("Dados de disseminação"),
    "infrastructure_directory": _("Dados de infraestrutura"),
    "policy_directory": _("Dados de Política"),
    "record_type": _("Tipo de registro"),
    "directory_type": _("Dados"),
    "countries": _("País"),
    "states": _("Estado"),
    "cities": _("Cidade"),
    "regions": _("Região"),
    "thematic_areas": _("Áreas temáticas"),
    "directory": _("Dados"),
    "indicator": _("Indicadores"),
    "practice": _("Práticas"),
    "action": _("Ações"),
    "category": _("Categoria"),
    "geo_scope": _("Escopo geográfico"),
    "thematic_scope": _("Escopo temático"),
    "institutional_contribution": _("Contribuição"),
    "CURRENT": _("Corrente"),
    "OUTDATED": _("Desatualizado"),
    "curso livre": _("curso livre"),
    "disciplina de graduação": _("disciplina de graduação"),
    "disciplina de lato sensu": _("disciplina de lato sensu"),
    "disciplina de stricto sensu": _("disciplina de stricto sensu"),
    "encontro": _("encontro"),
    "conferência": _("conferência"),
    "congresso": _("congresso"),
    "workshop": _("workshop"),
    "seminário": _("seminário"),
    "outros": _("outros"),
    "portal": _("Portal"),
    "plataforma": _("Plataforma"),
    "servidor": _("Servidor"),
    "repositório": _("Repositório"),
    "serviço": _("Serviço"),
    "promoção": _("promoção"),
    "posicionamento": _("posicionamento"),
    "mandato": _("mandato"),
    "geral": _("geral"),
    "outras": _("Outras"),
    "FREQUENCY": _("Frequência"),
    "EVOLUTION": _("Evolução"),
    "AVERAGE": _("Média"),
    "RELATIVE_FREQUENCY": _("Frequência relativa"),
    "GENERAL": _("Geral"),
    "INSTITUTIONAL": _("Instituticional"),
    "GEOGRAPHIC": _("Geográfico"),
    "CHRONOLOGICAL": _("Cronológico"),
    "THEMATIC": _("Temático"),
}
