from django.utils.translation import gettext as _

translates = {
    "education_directory": _("dados de educação"),
    "event_directory": _("dados de disseminação"),
    "infrastructure_directory": _("dados de infraestrutura"),
    "policy_directory": _("dados de Política"),
    "record_type": _("tipo de registro"),
    "directory_type": _("dados"),
    "countries": _("país"),
    "states": _("estado"),
    "cities": _("cidade"),
    "regions": _("região"),
    "thematic_areas": _("áreas temáticas"),
    "directory": _("Dados"),
    "indicator": _("Indicadores"),
    "practice": _("Práticas"),
    "action": _("Ações"),
    "category": _("Categoria"),
    "geo_scope": _("Escopo geográfico"),
    "thematic_scope": _("Escopo temático"),
    "institutional_contribution": _("Contribuição"),
    "CURRENT": _("Corrente"),
    "OUTDATED": _("Desatualizado"),
    "curso livre": _("curso livre"),
    "disciplina de graduação": _("disciplina de graduação"),
    "disciplina de lato sensu": _("disciplina de lato sensu"),
    "disciplina de stricto sensu": _("disciplina de stricto sensu"),
    "encontro": _("encontro"),
    "conferência": _("conferência"),
    "congresso": _("congresso"),
    "workshop": _("workshop"),
    "seminário": _("seminário"),
    "outros": _("outros"),
    "portal": _("Portal"),
    "plataforma": _("Plataforma"),
    "servidor": _("Servidor"),
    "repositório": _("Repositório"),
    "serviço": _("Serviço"),
    "promoção": _("promoção"),
    "posicionamento": _("posicionamento"),
    "mandato": _("mandato"),
    "geral": _("geral"),
    "outras": _("Outras"),
    "FREQUENCY": _("Frequência"),
    "EVOLUTION": _("Evolução"),
    "AVERAGE": _("Média"),
    "RELATIVE_FREQUENCY": _("Frequência relativa"),
    "GENERAL": _("Geral"),
    "INSTITUTIONAL": _("Instituticional"),
    "GEOGRAPHIC": _("Geográfico"),
    "CHRONOLOGICAL": _("Cronológico"),
    "THEMATIC": _("Temático"),
    "closed": _("Fechado"),
    "gold": _("Ouro"),
    "bronze": _("Bronze"),
    "hybrid": _("Hibrído"),
    "green": _("Verde"),
    "diamond": _("Diamante"),
    "year": _("Ano"),
    "true": _("Sim"),
    "false": _("Não"),
    "article": _("Artigo"),
    "book": _("Livro"),
    "bookchapter": _("Capítulo de livro"),
    "chapter": _("Capítulo"),
    "editorial": _("Editorial"),
    "dissertation": _("Dissertação"),
    "paratext": _("Paratexto"),
    "dataset": _("Conjunto de dados"),
    "erratum": _("Errata"),
    "other": _("Outro"),
    "others": _("Outros"),
    "report": _("Relatório"),
    "entry": _("Verbete"),
    "reference": _("Referência"),
    "referenceentry": _("Entrada de referência"),
    "journal": _("Periódico"),
    "journalarticle": _("Artigo de periódico"),
    "peer": _("Pares"),
    "peerreview": _("Revisão por pares"),
    "review": _("Revisão"),
    "letter": _("Carta"),
    "proceedings": _("Anais"),
    "content": _("Conteúdo"),
    "posted": _("Publicado"),
    "postedcontent": _("Conteúdo publicado"),
    "proceedingsarticle": _("Artigo de anais"),
    "standard": _("Norma"),
    "bookpart": _("Parte de livro"),
    "part": _("Parte"),
    "proceedingsseries": _("Série de anais"),
    "series": _("Série"),
    "year": "ano",
    "thematic_level_0": "área temática",
    "regions": "região",
    "open_access_status": "tipo de acesso aberto",
    "license": "licença",
    "open_access_status": "tipo de acesso aberto",
    "is_oa": "acesso aberto",
    "type": "tipo de documento",
    "brazil": "Brasil",
    "world": "Mundo",
    "world_region": "Mundo - região",
    "world_country": "Mundo - país",
    "brazil_region": "Brasil - região",
    "brazil_state": "Brasil - estado",
    "brazil_instituion": "Brasil - instituição",
    "literatura em acesso aberto": "Literatura em acesso aberta",
    "menção genérica à CA ou todas as práticas": "Menção genérica à CA ou todas as práticas",
    "outras práticas": "Outras práticas",
    "recursos educacionais abertos": "Recursos educacionais abertos",
    "dados abertos de pesquisa": "Dados abertos de pesquisa",
    "ciência cidadã": "Ciência cidadã",
    "peer review aberto": "Peer review aberto"
}


country_list = [
    ("United States of America", "US"),
    ("China", "ch"),
    ("United Kingdom of Great Britain and Northern Ireland", ""),
    ("Germany", ""),
    ("Japan", ""),
    ("France", ""),
    ("India", ""),
    ("Canada", ""),
    ("Italy", ""),
    ("Brazil", ""),
    ("Australia", ""),
    ("Spain", ""),
    ("Russian Federation", ""),
    ("Indonesia", ""),
    ("Netherlands", ""),
    ("Korea, Republic of", ""),
    ("Poland", ""),
    ("Switzerland", ""),
    ("Turkey", ""),
    ("Sweden", ""),
    ("Belgium", ""),
    ("Iran, Islamic Republic of", ""),
    ("Taiwan, Province of China", ""),
    ("Mexico", ""),
    ("Denmark", ""),
    ("Austria", ""),
    ("Israel", ""),
    ("Portugal", ""),
    ("Norway", ""),
    ("Czechia", ""),
    ("Finland", ""),
    ("South Africa", ""),
    ("Malaysia", ""),
    ("Egypt", ""),
    ("Greece", ""),
    ("Singapore", ""),
    ("Argentina", ""),
    ("Ukraine", ""),
    ("Saudi Arabia", ""),
    ("New Zealand", ""),
    ("Pakistan", ""),
    ("Colombia", ""),
    ("Ireland", ""),
    ("Hungary", ""),
    ("Chile", ""),
    ("Hong Kong", ""),
    ("Nigeria", ""),
    ("Romania", ""),
    ("Thailand", ""),
    ("Croatia", ""),
    ("Slovakia", ""),
    ("Bangladesh", ""),
    ("Serbia", ""),
    ("Viet Nam", ""),
    ("Iraq", ""),
    ("Bulgaria", ""),
    ("Slovenia", ""),
    ("Peru", ""),
    ("Morocco", ""),
    ("Tunisia", ""),
    ("Algeria", ""),
    ("Cuba", ""),
    ("United Arab Emirates", ""),
    ("Panama", ""),
    ("Philippines", ""),
    ("Ecuador", ""),
    ("Kenya", ""),
    ("Ethiopia", ""),
    ("Venezuela, Bolivarian Republic of", ""),
    ("Jordan", ""),
    ("Lithuania", ""),
    ("Ghana", ""),
    ("Nepal", ""),
    ("Qatar", ""),
    ("Kazakhstan", ""),
    ("Belarus", ""),
    ("Estonia", ""),
    ("Costa Rica", ""),
    ("Lebanon", ""),
    ("Cyprus", ""),
    ("Sri Lanka", ""),
    ("Uzbekistan", ""),
    ("Luxembourg", ""),
    ("Latvia", ""),
    ("Uruguay", ""),
    ("Tanzania, United Republic of", ""),
    ("Puerto Rico", ""),
    ("Uganda", ""),
    ("Cameroon", ""),
    ("Kuwait", ""),
    ("Oman", ""),
    ("Macao", ""),
    ("Azerbaijan", ""),
    ("Iceland", ""),
    ("Bosnia and Herzegovina", ""),
    ("Georgia", ""),
    ("Armenia", ""),
    ("Bolivia, Plurinational State of", ""),
    ("Sudan", ""),
    ("Mongolia", ""),
    ("North Macedonia", ""),
    ("Zimbabwe", ""),
    ("Tajikistan", ""),
    ("Senegal", ""),
    ("Moldova, Republic of", ""),
    ("Côte d'Ivoire", ""),
    ("Yemen", ""),
    ("Zambia", ""),
    ("South Sudan", ""),
    ("Cambodia", ""),
    ("Malta", ""),
    ("Palestine, State of", ""),
    ("Paraguay", ""),
    ("Mozambique", ""),
    ("Benin", ""),
    ("Guatemala", ""),
    ("Burkina Faso", ""),
    ("Bahrain", ""),
    ("Malawi", ""),
    ("Albania", ""),
    ("Mali", ""),
    ("Myanmar", ""),
    ("Libya", ""),
    ("Syrian Arab Republic", ""),
    ("Congo, Democratic Republic of the", ""),
    ("Botswana", ""),
    ("Niger", ""),
    ("Jamaica", ""),
    ("Réunion", ""),
    ("Brunei Darussalam", ""),
    ("Burundi", ""),
    ("Virgin Islands, British", ""),
    ("Rwanda", ""),
    ("Montenegro", ""),
    ("Trinidad and Tobago", ""),
    ("Congo", ""),
    ("Kosovo", ""),
    ("El Salvador", ""),
    ("Nicaragua", ""),
    ("Kyrgyzstan", ""),
    ("Honduras", ""),
    ("Madagascar", ""),
    ("Dominican Republic", ""),
    ("Namibia", ""),
    ("Fiji", ""),
    ("Mauritius", ""),
    ("Guadeloupe", ""),
    ("Afghanistan", ""),
    ("Papua New Guinea", ""),
    ("Togo", ""),
    ("Angola", ""),
    ("Gambia", ""),
    ("Gabon", ""),
    ("Grenada", ""),
    ("Guinea", ""),
    ("Lao People's Democratic Republic", ""),
    ("Monaco", ""),
    ("Barbados", ""),
    ("Sierra Leone", ""),
    ("Liechtenstein", ""),
    ("Sao Tome and Principe", ""),
    ("New Caledonia", ""),
    ("French Polynesia", ""),
    ("Martinique", ""),
    ("Greenland", ""),
    ("French Guiana", ""),
    ("Bhutan", ""),
    ("Guam", ""),
    ("Eswatini", ""),
    ("Antigua and Barbuda", ""),
    ("Haiti", ""),
    ("Chad", ""),
    ("Saint Martin (French part)", ""),
    ("Bahamas", ""),
    ("Guyana", ""),
    ("Guinea-Bissau", ""),
    ("Somalia", ""),
    ("Saint Kitts and Nevis", ""),
    ("Lesotho", ""),
    ("Curaçao", ""),
    ("Liberia", ""),
    ("Turkmenistan", ""),
    ("Maldives", ""),
    ("Faroe Islands", ""),
    ("Virgin Islands, U.S.", ""),
    ("Bermuda", ""),
    ("Suriname", ""),
    ("Gibraltar", ""),
    ("Belize", ""),
    ("Central African Republic", ""),
    ("Mauritania", ""),
    ("Eritrea", ""),
    ("Cayman Islands", ""),
    ("Dominica", ""),
    ("Korea, Democratic People's Republic of", ""),
    ("Seychelles", ""),
    ("Cabo Verde", ""),
    ("Timor-Leste", ""),
    ("Holy See", ""),
    ("Isle of Man" ""),
]

scimago_region = {
    "Western Europe": [
        "AD",
        "AT",
        "BE",
        "BV",
        "CY",
        "DK",
        "FO",
        "FI",
        "FR",
        "DE",
        "GI",
        "GR",
        "GL",
        "GG",
        "VA",
        "IS",
        "IE",
        "IM",
        "IT",
        "JE",
        "LI",
        "LU",
        "MT",
        "MC",
        "NL",
        "NO",
        "PT",
        "SM",
        "ES",
        "SJ",
        "SE",
        "CH",
        "GB",
        "AX",
    ],
    "Pacific Region": [
        "AS",
        "AU",
        "CX",
        "CC",
        "CK",
        "FJ",
        "PF",
        "TF",
        "GU",
        "HM",
        "KI",
        "MH",
        "FM",
        "NR",
        "NC",
        "NZ",
        "NU",
        "NF",
        "PW",
        "PG",
        "PN",
        "WS",
        "SB",
        "TK",
        "TO",
        "TV",
        "VU",
        "WF",
    ],
    "Northern America": ["CA", "PM", "UM", "US"],
    "Middle East": [
        "BH",
        "IR",
        "IQ",
        "IL",
        "JO",
        "KW",
        "LB",
        "OM",
        "PS",
        "QA",
        "SA",
        "SY",
        "TR",
        "AE",
        "YE",
    ],
    "Latin America": [
        "AI",
        "AG",
        "AR",
        "AW",
        "BS",
        "BB",
        "BZ",
        "BM",
        "BO",
        "BQ",
        "BR",
        "KY",
        "CL",
        "CO",
        "CR",
        "CU",
        "CW",
        "DM",
        "DO",
        "EC",
        "SV",
        "FK",
        "GF",
        "GD",
        "GP",
        "GT",
        "GY",
        "HT",
        "HN",
        "JM",
        "MQ",
        "MX",
        "MS",
        "NI",
        "PA",
        "PY",
        "PE",
        "PR",
        "BL",
        "KN",
        "LC",
        "MF",
        "VC",
        "SX",
        "GS",
        "SR",
        "TT",
        "TC",
        "UY",
        "VE",
        "VG",
        "VI",
    ],
    "Eastern Europe": [
        "AL",
        "AM",
        "AZ",
        "BY",
        "BA",
        "BG",
        "HR",
        "CZ",
        "EE",
        "GE",
        "HU",
        "LV",
        "LT",
        "MD",
        "ME",
        "MK",
        "PL",
        "RO",
        "RU",
        "RS",
        "SK",
        "SI",
        "UA",
        "XK",
    ],
    "Asiatic Region": [
        "AF",
        "BD",
        "BT",
        "BN",
        "KH",
        "CN",
        "HK",
        "IN",
        "ID",
        "JP",
        "KZ",
        "KP",
        "KR",
        "KG",
        "LA",
        "MO",
        "MY",
        "MV",
        "MN",
        "MM",
        "NP",
        "MP",
        "PK",
        "PH",
        "SG",
        "LK",
        "TW",
        "TJ",
        "TH",
        "TL",
        "TM",
        "UZ",
        "VN",
    ],
    "Antarctica": ["QA"],
    "Africa": [
        "DZ",
        "AO",
        "BJ",
        "BW",
        "IO",
        "BF",
        "BI",
        "CV",
        "CM",
        "CF",
        "TD",
        "KM",
        "CG",
        "CD",
        "CI",
        "DJ",
        "EG",
        "GQ",
        "ER",
        "SZ",
        "ET",
        "GA",
        "GM",
        "GH",
        "GN",
        "GW",
        "KE",
        "LS",
        "LR",
        "LY",
        "MG",
        "MW",
        "ML",
        "MR",
        "MU",
        "YT",
        "MA",
        "MZ",
        "NA",
        "NE",
        "NG",
        "RW",
        "RE",
        "SH",
        "ST",
        "SN",
        "SC",
        "SL",
        "SO",
        "ZA",
        "SS",
        "SD",
        "TZ",
        "TG",
        "TN",
        "UG",
        "EH",
        "ZM",
        "ZW",
    ],
}
