# Generated by Django 4.1.6 on 2023-04-19 11:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moderation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "custom_setting",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation",
                        to="core_settings.customsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation",
                "verbose_name_plural": "Moderations",
            },
        ),
    ]
