# Generated by Django 3.2.12 on 2022-07-22 16:16

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0003_customsettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
