# Generated by Django 4.1.6 on 2023-04-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0003_moderation_send_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderation",
            name="send_mail",
            field=models.BooleanField(
                default=True, verbose_name="Enviar e-mail para o moderador"
            ),
        ),
    ]
