# Generated by Django 4.1.6 on 2023-04-19 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_settings", "0004_alter_moderation_send_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderation",
            name="group_moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_group_moderator",
                to="auth.group",
                verbose_name="Grupo Moderator",
            ),
        ),
        migrations.AddField(
            model_name="moderation",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_moderator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Moderator",
            ),
        ),
        migrations.AlterField(
            model_name="moderation",
            name="send_mail",
            field=models.BooleanField(
                default=True,
                help_text="This field indicate if any record is create if must send e-mail to moderator or a group of moderators",
                verbose_name="Enviar e-mail para o moderador(es)",
            ),
        ),
    ]
