# Generated by Django 3.2.12 on 2022-08-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0004_auto_20220722_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsettings',
            options={'verbose_name': 'Configuração do site', 'verbose_name_plural': 'Configuração do site'},
        ),
    ]
