# Generated by Django 4.1.6 on 2023-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_settings",
            "0005_moderation_group_moderator_moderation_moderator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moderation",
            name="model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("indicator", "Indicatores"),
                    ("education_directory", "Diretório de educação"),
                    ("event_directory", "Diretório de divulgação"),
                    ("infrastructure_directory", "Diretório de infraestrutura"),
                    ("policy_directory", "Diretório de Política"),
                ],
                help_text="Indicate which model should be moderated",
                max_length=255,
                null=True,
                verbose_name="Model",
            ),
        ),
    ]
