# Generated by Django 4.1.6 on 2023-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0006_moderation_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderation",
            name="model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Indicator", "Indicatores"),
                    ("EducationDirectory", "Diretório de Educação"),
                    ("EventDirectory", "Diretório de Divulgação"),
                    ("InfrastructureDirectory", "Diretório de Infraestrutura"),
                    ("PolicyDirectory", "Diretório de Política"),
                ],
                help_text="Indicate which model should be moderated",
                max_length=255,
                null=True,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="moderation",
            name="send_mail",
            field=models.BooleanField(
                default=True,
                help_text="This field indicate if any record is create if must send e-mail to moderator or a group of moderators",
                verbose_name="Send e-mail to moderator(s)",
            ),
        ),
    ]
