# Generated by Django 4.1.6 on 2023-04-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0007_alter_moderation_model_alter_moderation_send_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderation",
            name="status",
            field=models.BooleanField(
                default=True,
                help_text="Set to False to disable the moderation",
                verbose_name="Enabled",
            ),
        ),
    ]
