# Generated by Django 4.1.6 on 2023-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0008_moderation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderation",
            name="send_mail",
            field=models.BooleanField(
                default=True,
                help_text="This field indicate if any record is create and if must send e-mail to moderator or a group of moderators",
                verbose_name="Send e-mail to moderator(s)",
            ),
        ),
    ]
