# Generated by Django 4.1.6 on 2025-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0009_alter_moderation_send_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsettings",
            name="embed_dash",
            field=models.TextField(
                blank=True, null=True, verbose_name="Embed Dashboard"
            ),
        ),
    ]
