# Generated by Django 5.2.10 on 2026-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtlItemProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_index", models.CharField(db_index=True, max_length=255)),
                ("external_id", models.CharField(max_length=255)),
                ("document_type", models.CharField(db_index=True, max_length=50)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("source_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("merged", "Merged"),
                            ("unchanged", "Unchanged"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="etl_etlitem_status_ca1d6f_idx"
                    ),
                    models.Index(
                        fields=["document_type", "publication_year"],
                        name="etl_etlitem_documen_262f75_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="etl_etlitem_updated_adbb3d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_index", "external_id"),
                        name="uniq_etl_item_source_external_id",
                    )
                ],
            },
        ),
    ]
