# Generated by Django 5.2.10 on 2026-05-12

from django.db import migrations, models


PIPELINE_CONFIGS = [
    {
        "name": "article",
        "enabled": True,
        "input_index": "bronze_scielo_articles*",
        "silver_index_pattern": "silver",
        "input_document_kind": "article",
        "default_document_type": "article",
        "infer_document_type_from_payload": True,
        "deduplicate_scielo": True,
        "openalex_index": "raw_openalex_works",
        "rules": {
            "scielo_dedup_strategies": ["doi", "pid", "fuzzy"],
            "openalex_match_strategies": ["doi", "isbn", "title"],
            "doi_requires_title_overlap": True,
            "pid_requires_year_match": True,
            "pid_requires_source_match": True,
            "pid_requires_title_overlap": True,
            "fuzzy_min_similarity": 0.85,
            "fuzzy_year_tolerance": 1,
            "fuzzy_requires_source_match": True,
            "openalex_validation": {
                "year_tolerance": 1,
                "require_openalex_year": True,
                "require_source_match": False,
                "source_similarity_threshold": 0.80,
                "title_match_threshold": 0.85,
                "title_reject_threshold": 0.80,
                "min_score": 50,
                "strict_min_score": 60,
                "doi_score": 50,
                "year_exact_score": 30,
                "year_close_score": 20,
                "isbn_score": 35,
                "source_id_score": 40,
                "source_title_score": 30,
                "title_score": 30,
                "isbn_requires_title_match": False,
                "isbn_title_threshold": 0.80,
            },
        },
    },
    {
        "name": "book",
        "enabled": True,
        "input_index": "bronze_scielo_books",
        "silver_index_pattern": "silver",
        "input_document_kind": "book",
        "default_document_type": "book",
        "infer_document_type_from_payload": True,
        "deduplicate_scielo": False,
        "openalex_index": "raw_openalex_works",
        "rules": {
            "scielo_dedup_strategies": [],
            "openalex_match_strategies": ["doi", "isbn", "title"],
            "doi_requires_title_overlap": True,
            "pid_requires_year_match": True,
            "pid_requires_source_match": False,
            "pid_requires_title_overlap": True,
            "fuzzy_min_similarity": 0.88,
            "fuzzy_year_tolerance": 1,
            "fuzzy_requires_source_match": False,
            "openalex_validation": {
                "year_tolerance": 1,
                "require_openalex_year": True,
                "require_source_match": False,
                "source_similarity_threshold": 0.80,
                "title_match_threshold": 0.85,
                "title_reject_threshold": 0.80,
                "min_score": 50,
                "strict_min_score": 60,
                "doi_score": 50,
                "year_exact_score": 30,
                "year_close_score": 20,
                "isbn_score": 35,
                "source_id_score": 40,
                "source_title_score": 30,
                "title_score": 30,
                "isbn_requires_title_match": False,
                "isbn_title_threshold": 0.80,
            },
        },
    },
    {
        "name": "book-chapter",
        "enabled": True,
        "input_index": "bronze_scielo_books",
        "silver_index_pattern": "silver",
        "input_document_kind": "book",
        "default_document_type": "book-chapter",
        "infer_document_type_from_payload": True,
        "deduplicate_scielo": False,
        "openalex_index": "raw_openalex_works",
        "rules": {
            "scielo_dedup_strategies": [],
            "openalex_match_strategies": ["doi", "isbn", "title"],
            "doi_requires_title_overlap": True,
            "pid_requires_year_match": True,
            "pid_requires_source_match": False,
            "pid_requires_title_overlap": True,
            "fuzzy_min_similarity": 0.90,
            "fuzzy_year_tolerance": 1,
            "fuzzy_requires_source_match": False,
            "openalex_validation": {
                "year_tolerance": 1,
                "require_openalex_year": True,
                "require_source_match": False,
                "source_similarity_threshold": 0.80,
                "title_match_threshold": 0.85,
                "title_reject_threshold": 0.80,
                "min_score": 50,
                "strict_min_score": 60,
                "doi_score": 50,
                "year_exact_score": 30,
                "year_close_score": 20,
                "isbn_score": 35,
                "source_id_score": 40,
                "source_title_score": 30,
                "title_score": 30,
                "isbn_requires_title_match": True,
                "isbn_title_threshold": 0.80,
            },
        },
    },
    {
        "name": "preprint",
        "enabled": True,
        "input_index": "bronze_scielo_preprint",
        "silver_index_pattern": "silver",
        "input_document_kind": "preprint",
        "default_document_type": "preprint",
        "infer_document_type_from_payload": False,
        "deduplicate_scielo": False,
        "openalex_index": "raw_openalex_works",
        "rules": {
            "scielo_dedup_strategies": [],
            "openalex_match_strategies": ["doi", "title"],
            "doi_requires_title_overlap": True,
            "pid_requires_year_match": True,
            "pid_requires_source_match": False,
            "pid_requires_title_overlap": True,
            "fuzzy_min_similarity": 0.88,
            "fuzzy_year_tolerance": 1,
            "fuzzy_requires_source_match": False,
            "openalex_validation": {
                "year_tolerance": 1,
                "require_openalex_year": True,
                "require_source_match": False,
                "source_similarity_threshold": 0.80,
                "title_match_threshold": 0.88,
                "title_reject_threshold": 0.82,
                "min_score": 50,
                "strict_min_score": 60,
                "doi_score": 50,
                "year_exact_score": 30,
                "year_close_score": 20,
                "isbn_score": 35,
                "source_id_score": 40,
                "source_title_score": 30,
                "title_score": 30,
                "isbn_requires_title_match": False,
                "isbn_title_threshold": 0.80,
            },
        },
    },
    {
        "name": "dataset",
        "enabled": True,
        "input_index": "bronze_scielo_dataset",
        "silver_index_pattern": "silver",
        "input_document_kind": "dataset",
        "default_document_type": "dataset",
        "infer_document_type_from_payload": False,
        "deduplicate_scielo": False,
        "openalex_index": "raw_openalex_works",
        "rules": {
            "scielo_dedup_strategies": [],
            "openalex_match_strategies": ["doi"],
            "doi_requires_title_overlap": True,
            "pid_requires_year_match": True,
            "pid_requires_source_match": False,
            "pid_requires_title_overlap": True,
            "fuzzy_min_similarity": 0.95,
            "fuzzy_year_tolerance": 0,
            "fuzzy_requires_source_match": False,
            "openalex_validation": {
                "year_tolerance": 1,
                "require_openalex_year": True,
                "require_source_match": False,
                "source_similarity_threshold": 0.80,
                "title_match_threshold": 0.90,
                "title_reject_threshold": 0.85,
                "min_score": 60,
                "strict_min_score": 70,
                "doi_score": 50,
                "year_exact_score": 30,
                "year_close_score": 20,
                "isbn_score": 35,
                "source_id_score": 40,
                "source_title_score": 30,
                "title_score": 30,
                "isbn_requires_title_match": False,
                "isbn_title_threshold": 0.80,
            },
        },
    },
]


def seed_pipeline_configs(apps, schema_editor):
    EtlPipelineConfig = apps.get_model("etl", "EtlPipelineConfig")
    for config in PIPELINE_CONFIGS:
        EtlPipelineConfig.objects.update_or_create(
            name=config["name"],
            defaults=config,
        )


def remove_pipeline_configs(apps, schema_editor):
    EtlPipelineConfig = apps.get_model("etl", "EtlPipelineConfig")
    EtlPipelineConfig.objects.filter(
        name__in=[config["name"] for config in PIPELINE_CONFIGS]
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtlItemProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_index", models.CharField(db_index=True, max_length=255)),
                ("external_id", models.CharField(max_length=255)),
                ("document_type", models.CharField(db_index=True, max_length=50)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("source_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("merged", "Merged"),
                            ("unchanged", "Unchanged"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pid_v2", models.CharField(blank=True, default="", max_length=255)),
                ("doi", models.CharField(blank=True, default="", max_length=500)),
                ("isbn", models.CharField(blank=True, default="", max_length=255)),
                (
                    "preprint_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dataset_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("has_openalex_match", models.BooleanField(default=False)),
                ("has_scielo_dedup", models.BooleanField(default=False)),
                ("scielo_dedup_ids", models.JSONField(blank=True, default=list)),
                ("openalex_match_ids", models.JSONField(blank=True, default=list)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="etl_etlitem_status_ca1d6f_idx"
                    ),
                    models.Index(
                        fields=["document_type", "publication_year"],
                        name="etl_etlitem_documen_262f75_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="etl_etlitem_updated_adbb3d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_index", "external_id"),
                        name="uniq_etl_item_source_external_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EtlPipelineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("input_index", models.CharField(db_index=True, max_length=255)),
                ("silver_index_pattern", models.CharField(max_length=255)),
                (
                    "input_document_kind",
                    models.CharField(
                        choices=[
                            ("article", "SciELO Article"),
                            ("book", "SciELO Book"),
                            ("preprint", "SciELO Preprint"),
                            ("dataset", "SciELO Dataset"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_document_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("book", "Book"),
                            ("book-chapter", "Book chapter"),
                            ("preprint", "Preprint"),
                            ("dataset", "Dataset"),
                        ],
                        max_length=30,
                    ),
                ),
                ("infer_document_type_from_payload", models.BooleanField(default=False)),
                ("deduplicate_scielo", models.BooleanField(default=False)),
                (
                    "openalex_index",
                    models.CharField(default="raw_openalex_works", max_length=255),
                ),
                ("rules", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "ETL Pipeline Config",
                "verbose_name_plural": "ETL Pipeline Configs",
            },
        ),
        migrations.RunPython(seed_pipeline_configs, remove_pipeline_configs),
    ]
