# Generated by Django 5.2.10 on 2026-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0002_remove_silver_index_pattern"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etlitemprocess",
            options={"verbose_name": "ETL Item Process"},
        ),
        migrations.AlterField(
            model_name="etlitemprocess",
            name="dataset_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Dataset ID"
            ),
        ),
        migrations.AlterField(
            model_name="etlitemprocess",
            name="document_type",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="ETL type"
            ),
        ),
        migrations.AlterField(
            model_name="etlitemprocess",
            name="doi",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="DOI"
            ),
        ),
        migrations.AlterField(
            model_name="etlitemprocess",
            name="isbn",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="etlitemprocess",
            name="pid_v2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="PID V2"
            ),
        ),
        migrations.AlterField(
            model_name="etlitemprocess",
            name="preprint_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Preprint ID"
            ),
        ),
        migrations.AlterField(
            model_name="etlpipelineconfig",
            name="openalex_index",
            field=models.CharField(default="silver_openalex-*", max_length=255),
        ),
    ]
