# Generated by Django 5.2.10 on 2026-09-29 16:09

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0003_update_etl_admin_labels_and_openalex_index_default"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="etlitemprocess",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("has_openalex_match", True)),
                fields=["openalex_match_ids"],
                name="etl_item_oa_ids_gin",
            ),
        ),
    ]
