# Generated by Django 5.2.10 on 2026-05-12 22:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search_gateway", "0004_alter_datasource_field_settings"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Texto de introdução."
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fonte de dados do OpenSearch vinculada a este indicador.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="search_gateway.datasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="IndicatorByCategoryPage",
            fields=[
                (
                    "indicatorpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="indicator_journal.indicatorpage",
                    ),
                ),
                (
                    "default_category_level",
                    models.CharField(
                        blank=True,
                        help_text="Ex: field, subfield, topic, domain",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "default_publication_year",
                    models.CharField(
                        blank=True,
                        help_text="Ano de publicação padrão (ex: 2024)",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "default_ranking_metric",
                    models.CharField(
                        blank=True,
                        help_text="Métrica de ranking padrão",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("indicator_journal.indicatorpage",),
        ),
        migrations.CreateModel(
            name="IndicatorGlobalPage",
            fields=[
                (
                    "indicatorpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="indicator_journal.indicatorpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("indicator_journal.indicatorpage",),
        ),
    ]
