# Generated by Django 5.2.10 on 2026-06-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator_journal", "0001_initial"),
        ("search_gateway", "0005_datasource_metric_config"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalProfilePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "show_global_metrics",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Enable the Global Metrics tab on the profile page. "
                            "Only turn on when the global index is ready."
                        ),
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="DataSource with journal metrics.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="search_gateway.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Profile Page",
                "verbose_name_plural": "Journal Profile Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]