# Generated by Django 3.2.12 on 2022-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructuredirectory',
            name='name',
        ),
        migrations.AddField(
            model_name='infrastructuredirectory',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
