# Generated by Django 3.2.12 on 2022-07-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0002_auto_20220628_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructuredirectory',
            options={'verbose_name_plural': 'Infraestructure Directory'},
        ),
        migrations.AlterModelOptions(
            name='infrastructuredirectoryfile',
            options={'verbose_name_plural': 'Infraestructure Directory Upload'},
        ),
    ]
