# Generated by Django 3.2.12 on 2022-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0002_alter_infrastructuredirectory_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WORK IN PROGRESS'), ('TO MODERATE', 'TO MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
    ]
