# Generated by Django 3.2.12 on 2022-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0003_alter_infrastructuredirectory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuredirectory',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Data de fim'),
        ),
        migrations.AddField(
            model_name='infrastructuredirectory',
            name='end_time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='Hora final'),
        ),
        migrations.AddField(
            model_name='infrastructuredirectory',
            name='start_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Data de início'),
        ),
        migrations.AddField(
            model_name='infrastructuredirectory',
            name='start_time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='Hora inicial'),
        ),
    ]
