# Generated by Django 3.2.12 on 2022-08-09 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('infrastructure_directory', '0003_auto_20220705_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructuredirectory',
            options={'verbose_name_plural': 'Diretório de Infraestrutura'},
        ),
        migrations.AlterModelOptions(
            name='infrastructuredirectoryfile',
            options={'verbose_name_plural': 'Diretório de Infraestrutura Upload'},
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructuredirectory_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructuredirectory_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructuredirectoryfile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É válido'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='line_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de linhas'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectoryfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructuredirectoryfile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
    ]
