# Generated by Django 4.1.6 on 2023-04-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure_directory",
            "0004_alter_infrastructuredirectory_creator_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infrastructuredirectory",
            options={
                "permissions": (("must_be_moderate", "Must be moderated"),),
                "verbose_name_plural": "Diretório de Infraestrutura",
            },
        ),
    ]
