# Generated by Django 3.2.12 on 2022-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0004_auto_20221004_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WORK IN PROGRESS'), ('TO MODERATE', 'TO MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
    ]
