# Generated by Django 3.2.12 on 2022-08-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0005_infrastructuredirectory_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructuredirectory',
            old_name='institution',
            new_name='institutions',
        ),
    ]
