# Generated by Django 4.1.6 on 2023-05-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure_directory",
            "0007_infrastructuredirectory_institutional_contribution",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="institutional_contribution",
            field=models.CharField(
                default="SciELO",
                help_text="Name of the contributing institution, default=SciELO.",
                max_length=255,
                verbose_name="Institutional Contribution",
            ),
        ),
    ]
