# Generated by Django 3.2.12 on 2022-08-19 13:31

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('infrastructure_directory', '0009_auto_20220817_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='classification',
            field=models.CharField(blank=True, choices=[('', ''), ('portal', 'Portal'), ('plataforma', 'Plataforma'), ('servidor', 'Servidor'), ('repositório', 'Repositório'), ('serviço', 'Serviço'), ('outras', 'Outras')], max_length=255, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='infrastructuredirectory',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
