# Generated by Django 4.1.6 on 2023-07-14 16:47

from django.db import migrations, models
import django.db.models.deletion
import infrastructure_directory.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("institution", "0005_alter_institution_creator_and_more"),
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("infrastructure_directory", "0010_alter_infrastructuredirectory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infrastructuredirectory",
            options={
                "permissions": (
                    ("must_be_moderate", "Must be moderated"),
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_link", "Can edit link"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_institutions", "Can edit institutions"),
                    ("can_edit_thematic_areas", "Can edit thematic_areas"),
                    ("can_edit_practice", "Can edit practice"),
                    ("can_edit_action", "Can edit action"),
                    ("can_edit_classification", "Can edit classification"),
                    ("can_edit_keywords", "Can edit keywords"),
                    ("can_edit_record_status", "Can edit record_status"),
                    ("can_edit_source", "Can edit source"),
                    (
                        "can_edit_institutional_contribution",
                        "Can edit institutional_contribution",
                    ),
                    ("can_edit_notes", "Can edit notes"),
                ),
                "verbose_name": "Infrastructure Data",
                "verbose_name_plural": "Infrastructure Data",
            },
        ),
        migrations.AlterModelOptions(
            name="infrastructuredirectoryfile",
            options={
                "verbose_name": "Infrastructure Data Upload",
                "verbose_name_plural": "Infrastructure Data Upload",
            },
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="action",
            field=models.ForeignKey(
                blank=True,
                default=infrastructure_directory.models.get_default_action,
                help_text="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.action",
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("portal", "Portal"),
                    ("plataforma", "Plataforma"),
                    ("servidor", "Servidor"),
                    ("repositório", "Repositório"),
                    ("serviço", "Serviço"),
                    ("outras", "Outras"),
                ],
                help_text='Classificação referente ao item registrado. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#classifica%C3%A7%C3%A3o" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#classifica%C3%A7%C3%A3o</a>',
                max_length=255,
                null=True,
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='Descrição/representação do item, veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#descri%C3%A7%C3%A3o" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#descri%C3%A7%C3%A3o</a>',
                max_length=1000,
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="institutional_contribution",
            field=models.CharField(
                default="SciELO",
                help_text='Nome da instituição que contribuiu. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#institui%C3%A7%C3%A3o-contribuidora" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#institui%C3%A7%C3%A3o-contribuidora</a>',
                max_length=255,
                verbose_name="Institutional Contribution",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="institutions",
            field=models.ManyToManyField(
                blank=True,
                help_text='Instituição/empresa ao qual o item registrado pertence. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#institui%C3%A7%C3%A3o" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#institui%C3%A7%C3%A3o</a>',
                to="institution.institution",
                verbose_name="Instituição",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="keywords",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='Palavras-chaves do item. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#palavras-chaves" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#palavras-chaves</a>',
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Palavra-chave",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="link",
            field=models.URLField(
                help_text='Link URL do item específico, veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#link" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#link</a>',
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text='Anotações sobre o registro. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#notes" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#notes</a>',
                max_length=1000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="practice",
            field=models.ForeignKey(
                help_text='Prática da ciência aberta referente ao item registrado. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#pr%C3%A1tica" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#pr%C3%A1tica</a>',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="record_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("WIP", "WIP"),
                    ("TO MODERATE", "TO MODERATE"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("NOT PUBLISHED", "NOT PUBLISHED"),
                ],
                help_text='Status do registro no OCABR. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#status" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#status</a>',
                max_length=255,
                null=True,
                verbose_name="Record status",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="source",
            field=models.CharField(
                blank=True,
                help_text='Instituição a qual o item é subordinado (quando houver). É diferente da instituição. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#origem" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#origem</a>',
                max_length=255,
                null=True,
                verbose_name="Origem",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="thematic_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text='Grandes área do conhecimento ao qual pertence o item. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#%C3%A1rea-tem%C3%A1tica" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#%C3%A1rea-tem%C3%A1tica</a>',
                to="usefulmodels.thematicarea",
                verbose_name="Área temática",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="title",
            field=models.CharField(
                help_text='Título do item, veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#title" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#title</a>',
                max_length=255,
                verbose_name="Título",
            ),
        ),
    ]
