# Generated by Django 4.1.6 on 2023-05-25 10:37

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_creator_and_more"),
        ("taggit", "0005_auto_20220424_2025"),
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("infrastructure_directory", "0010_alter_infrastructuredirectory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infrastructuredirectory",
            options={
                "permissions": (
                    ("must_be_moderate", "Must be moderated"),
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_link", "Can edit link"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_locations", "Can edit locations"),
                    ("can_edit_institutions", "Can edit institutions"),
                    ("can_edit_thematic_areas", "Can edit thematic_areas"),
                    ("can_edit_practice", "Can edit practice"),
                    ("can_edit_action", "Can edit action"),
                    ("can_edit_classification", "Can edit classification"),
                    ("can_edit_keywords", "Can edit keywords"),
                    ("can_edit_record_status", "Can edit record_status"),
                    ("can_edit_source", "Can edit source"),
                    (
                        "can_edit_institutional_contribution",
                        "Can edit institutional_contribution",
                    ),
                    ("can_edit_notes", "Can edit notes"),
                ),
                "verbose_name": "Infrastructure Data",
                "verbose_name_plural": "Infrastructure Data",
            },
        ),
        migrations.AlterModelOptions(
            name="infrastructuredirectoryfile",
            options={
                "verbose_name": "Infrastructure Data Upload",
                "verbose_name_plural": "Infrastructure Data Upload",
            },
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="classification",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("portal", "Portal"),
                    ("plataforma", "Plataforma"),
                    ("servidor", "Servidor"),
                    ("repositório", "Repositório"),
                    ("serviço", "Serviço"),
                    ("outras", "Outras"),
                ],
                max_length=255,
                null=True,
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="description",
            field=models.TextField(
                max_length=1000, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="institutional_contribution",
            field=models.CharField(
                default="SciELO",
                help_text="Name of the contributing institution, default=SciELO.",
                max_length=255,
                null=True,
                verbose_name="Institutional Contribution",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="institutions",
            field=models.ManyToManyField(
                null=True, to="institution.institution", verbose_name="Instituição"
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="keywords",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Palavra-chave",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="practice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="source",
            field=models.CharField(max_length=255, null=True, verbose_name="Origem"),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="thematic_areas",
            field=models.ManyToManyField(
                null=True, to="usefulmodels.thematicarea", verbose_name="Área temática"
            ),
        ),
    ]
