# Generated by Django 3.2.12 on 2022-08-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0013_alter_infrastructuredirectory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructuredirectory',
            name='pratice',
        ),
    ]
