# Generated by Django 3.2.12 on 2022-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0015_infrastructuredirectory_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuredirectory',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WIP'), ('TO_MODERATE', 'TO_MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
    ]
