# Generated by Django 4.1.6 on 2026-01-09 07:56

from django.db import migrations, models
import django.db.models.deletion
import infrastructure_directory.models


class Migration(migrations.Migration):

    dependencies = [
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("infrastructure_directory", "0015_alter_infrastructuredirectory_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructuredirectory",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Data",
                max_length=255,
                null=True,
                verbose_name="Data",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="action",
            field=models.ForeignKey(
                blank=True,
                default=infrastructure_directory.models.get_default_action,
                help_text="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.action",
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuredirectory",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("portal", "Portal"),
                    ("plataforma", "Plataforma"),
                    ("servidor", "Servidor"),
                    ("repositório", "Repositório"),
                    ("repositório de dados", "Repositório de dados"),
                    (
                        "repositório de dados de pesquisa",
                        "Repositório de dados de pesquisa",
                    ),
                    ("portal de periódicos", "Portal de periódicos"),
                    ("websites", "Websites"),
                    ("serviço", "Serviço"),
                    ("outras", "Outras"),
                ],
                help_text='Classificação referente ao item registrado. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#classifica%C3%A7%C3%A3o" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#classifica%C3%A7%C3%A3o</a>',
                max_length=255,
                null=True,
                verbose_name="Classificação",
            ),
        ),
    ]
