# Generated by Django 3.2.12 on 2022-08-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0016_infrastructuredirectory_record_status'),
        ('infrastructure_directory', '0016_infrastructuredirectory_source'),
    ]

    operations = [
    ]
