# Generated by Django 4.1.6 on 2023-07-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("institution", "0005_alter_institution_creator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Nome de afiliação",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="DOI"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=510, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Volume"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "is_ao",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Is Open Access",
                    ),
                ),
                (
                    "open_access_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("gold", "Gold"),
                            ("hybrid", "Hybrid"),
                            ("bronze", "Bronze"),
                            ("green", "Green"),
                            ("closed", "Closed"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Open Access Status",
                    ),
                ),
                (
                    "apc",
                    models.CharField(
                        blank=True,
                        choices=[("", ""), ("YES", "YES"), ("NO", "NO")],
                        max_length=20,
                        null=True,
                        verbose_name="Article Processing Charge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Sobrenome"
                    ),
                ),
                (
                    "given",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nome dado"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ORCID"
                    ),
                ),
                (
                    "authenticated_orcid",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Autenticado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journal_issn_l",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ISSN-L"
                    ),
                ),
                (
                    "journal_issns",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ISSN's"
                    ),
                ),
                (
                    "journal_name",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Nome do periódico",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Publicador"
                    ),
                ),
                (
                    "journal_is_in_doaj",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="DOAJ"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of license, it is not required",
                        max_length=100,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "delay_in_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days between the publication date of the work and the start date of this license",
                        null=True,
                        verbose_name="Delay in Days",
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        help_text="Date on which this license begins to take effect",
                        max_length=100,
                        null=True,
                        verbose_name="Stard Date",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to a web page describing this license",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Source Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specific_id",
                    models.CharField(max_length=255, verbose_name="Specific Id"),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "is_paratext",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Paratext"
                    ),
                ),
                (
                    "doi",
                    models.CharField(max_length=100, null=True, verbose_name="DOI"),
                ),
                (
                    "updated",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Source updated date"
                    ),
                ),
                (
                    "created",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Source created date"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Arquivo JSON"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.source",
                        verbose_name="Origem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Program Name",
                    ),
                ),
                (
                    "affiliation",
                    models.ForeignKey(
                        blank=True,
                        max_length=1020,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="article.affiliation",
                        verbose_name="Affiliation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["journal_issn_l"], name="article_jou_journal_88bce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["journal_issns"], name="article_jou_journal_5dec9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["journal_name"], name="article_jou_journal_2d6f3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["publisher"], name="article_jou_publish_561e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["journal_is_in_doaj"], name="article_jou_journal_610072_idx"
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                max_length=510,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.affiliation",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="programs",
            field=models.ManyToManyField(
                blank=True, to="article.program", verbose_name="Program"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, to="article.contributor", verbose_name="Contribuidores"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.journal",
                verbose_name="Periódico",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.license",
                verbose_name="License",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="sources",
            field=models.ManyToManyField(
                blank=True, to="article.source", verbose_name="Origem"
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.country",
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="official",
            field=models.ForeignKey(
                blank=True,
                max_length=1020,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institution",
                verbose_name="Official Affiliation Name",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcearticle",
            index=models.Index(fields=["doi"], name="article_sou_doi_9c992b_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcearticle",
            index=models.Index(
                fields=["specific_id"], name="article_sou_specifi_580319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcearticle",
            index=models.Index(fields=["year"], name="article_sou_year_45dae5_idx"),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(fields=["family"], name="article_con_family_cb807c_idx"),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(fields=["given"], name="article_con_given_7f6681_idx"),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(fields=["orcid"], name="article_con_orcid_d49d0c_idx"),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["authenticated_orcid"], name="article_con_authent_80df26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["affiliation"], name="article_con_affilia_b56430_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["doi"], name="article_art_doi_2467f3_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["title"], name="article_art_title_d15895_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["volume"], name="article_art_volume_2f0e2c_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["number"], name="article_art_number_d21555_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["year"], name="article_art_year_b91cb0_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["open_access_status"], name="article_art_open_ac_a10b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["apc"], name="article_art_apc_cc7a3e_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["journal"], name="article_art_journal_8242e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(fields=["name"], name="article_aff_name_d033b1_idx"),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(
                fields=["country"], name="article_aff_country_08666d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(
                fields=["official"], name="article_aff_officia_3206b2_idx"
            ),
        ),
    ]
