# Generated by Django 4.1.6 on 2023-07-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="journal_issn_l",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ISSN-L"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_issns",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ISSN's"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_name",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Nome do periódico"
            ),
        ),
    ]
