# Generated by Django 4.1.6 on 2023-07-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_journal_journal_issn_l_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="journal_issn_l",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ISSN-L"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_issns",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ISSN's"
            ),
        ),
    ]
