# Generated by Django 4.1.6 on 2023-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_alter_journal_journal_issn_l_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="name",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Nome de afiliação"
            ),
        ),
    ]
