# Generated by Django 4.1.6 on 2023-07-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_alter_affiliation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="name",
            field=models.CharField(
                blank=True, max_length=5048, null=True, verbose_name="Nome de afiliação"
            ),
        ),
    ]
