# Generated by Django 4.1.6 on 2023-07-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_alter_affiliation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nome de afiliação"
            ),
        ),
    ]
