# Generated by Django 4.1.6 on 2023-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0009_alter_affiliation_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contributor",
            name="article_con_affilia_b56430_idx",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="affiliation",
        ),
        migrations.AddField(
            model_name="contributor",
            name="affiliations",
            field=models.ManyToManyField(
                blank=True, to="article.affiliation", verbose_name="Afiliações"
            ),
        ),
    ]
