# Generated by Django 4.1.6 on 2023-07-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0010_remove_contributor_article_con_affilia_b56430_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="affiliations_string",
            field=models.TextField(default="", verbose_name="Affiliations_string"),
            preserve_default=False,
        ),
    ]
