# Generated by Django 4.1.6 on 2023-07-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("article", "0012_alter_contributor_affiliations_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="sources",
            field=models.ManyToManyField(
                blank=True, to="core.source", verbose_name="Origem"
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="affiliations_string",
            field=models.TextField(
                blank=True, null=True, verbose_name="Affiliation String"
            ),
        ),
        migrations.AlterField(
            model_name="sourcearticle",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.source",
                verbose_name="Origem",
            ),
        ),
        migrations.DeleteModel(
            name="Source",
        ),
    ]
