# Generated by Django 4.1.6 on 2023-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0013_alter_article_sources_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcearticle",
            name="doi",
            field=models.CharField(max_length=255, null=True, verbose_name="DOI"),
        ),
    ]
