# Generated by Django 4.1.6 on 2023-10-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0014_alter_sourcearticle_doi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="is_ao",
            new_name="is_oa",
        ),
        migrations.AddField(
            model_name="contributor",
            name="author_position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="author_position"
            ),
        ),
    ]
