# Generated by Django 4.1.6 on 2023-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0011_institutiontranslatename_source_institution"),
        ("article", "0015_rename_is_ao_article_is_oa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="institutions",
            field=models.ManyToManyField(
                to="institution.sourceinstitution", verbose_name="Institutions"
            ),
        ),
    ]
