# Generated by Django 4.1.6 on 2023-10-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0012_merge_20231016_1606"),
        ("article", "0016_contributor_institutions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="affiliations_string",
        ),
        migrations.AddField(
            model_name="affiliation",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.sourceinstitution",
                verbose_name="Source Institution",
            ),
        ),
    ]
