# Generated by Django 4.1.6 on 2023-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0017_remove_contributor_affiliations_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nome de afiliação"
            ),
        ),
    ]
