# Generated by Django 4.1.6 on 2023-10-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_language"),
        ("article", "0018_alter_affiliation_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceConcepts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specific_id",
                    models.CharField(max_length=255, verbose_name="Specific Id"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the concept",
                        max_length=255,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the concept",
                        max_length=255,
                        null=True,
                        verbose_name="Normalized Name",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True,
                        help_text="Number indicating hierarchy",
                        null=True,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "parent_display_names",
                    models.CharField(
                        blank=True,
                        help_text="The name of parents up to child names",
                        max_length=255,
                        null=True,
                        verbose_name="Parent Display Name",
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="affiliation",
            name="article_aff_name_d033b1_idx",
        ),
        migrations.AddField(
            model_name="sourceconcepts",
            name="parent_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_id",
                to="article.sourceconcepts",
                verbose_name="Parent ids",
            ),
        ),
        migrations.AddField(
            model_name="sourceconcepts",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.source",
                verbose_name="Origem",
            ),
        ),
    ]
