# Generated by Django 4.1.6 on 2023-10-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_language"),
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("article", "0023_sourceconcepts_thematic_areas_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SourceConcepts",
            new_name="Concepts",
        ),
        migrations.AlterModelOptions(
            name="concepts",
            options={"verbose_name": "Concept", "verbose_name_plural": "Concepts"},
        ),
    ]
