# Generated by Django 4.1.6 on 2023-10-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_language"),
        ("article", "0024_rename_sourceconcepts_concepts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concepts",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.source",
                verbose_name="Origem",
            ),
        ),
    ]
