# Generated by Django 4.1.6 on 2023-11-24 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0026_article_concepts_article_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="creator",
            field=models.ForeignKey(
                default=None,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
    ]
