# Generated by Django 4.1.6 on 2023-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0026_article_concepts_article_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="concepts",
            name="program",
            field=models.ManyToManyField(
                blank=True, to="article.program", verbose_name="Program"
            ),
        ),
    ]
