# Generated by Django 4.1.6 on 2024-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0027_article_created_article_creator_article_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="raw",
            field=models.JSONField(blank=True, null=True, verbose_name="Arquivo JSON"),
        ),
    ]
