# Generated by Django 4.1.6 on 2024-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0030_sourcearticle_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tipo"
            ),
        ),
    ]
