# Generated by Django 3.2.12 on 2022-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_institution_location'),
        ('policy_directory', '0002_auto_20220809_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydirectory',
            name='institution',
        ),
        migrations.AddField(
            model_name='policydirectory',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='institution.Institution'),
        ),
    ]
