# Generated by Django 3.2.12 on 2022-11-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy_directory", "0002_alter_policydirectory_record_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policydirectory",
            name="date",
            field=models.DateField(
                blank=True, max_length=255, null=True, verbose_name="Data"
            ),
        ),
    ]
