# Generated by Django 3.2.12 on 2022-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_directory', '0003_alter_policydirectory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydirectory',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
