# Generated by Django 4.1.6 on 2023-04-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy_directory", "0005_alter_policydirectory_creator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policydirectory",
            options={
                "permissions": (("must_be_moderate", "Must be moderated"),),
                "verbose_name_plural": "Diretório de Política",
            },
        ),
    ]
