# Generated by Django 3.2.12 on 2022-08-22 13:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('institution', '0004_institution_acronym'),
        ('usefulmodels', '0013_auto_20220822_1346'),
        ('policy_directory', '0007_alter_policydirectory_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydirectory',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.action', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='policydirectory',
            name='classification',
            field=models.CharField(blank=True, choices=[('', ''), ('promoção', 'promoção'), ('posicionamento', 'posicionamento'), ('mandato', 'mandato'), ('geral', 'geral')], max_length=255, null=True, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='policydirectory',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='institution.Institution', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='policydirectory',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Palavra-chave'),
        ),
        migrations.AlterField(
            model_name='policydirectory',
            name='pratice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.pratice', verbose_name='Prática'),
        ),
        migrations.AlterField(
            model_name='policydirectory',
            name='thematic_areas',
            field=models.ManyToManyField(blank=True, to='usefulmodels.ThematicArea', verbose_name='Área temática'),
        ),
    ]
