# Generated by Django 3.2.12 on 2022-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_directory', '0008_auto_20220822_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydirectory',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição'),
        ),
    ]
