# Generated by Django 3.2.12 on 2022-08-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_directory', '0010_remove_policydirectory_pratice'),
        ('usefulmodels', '0014_auto_20220825_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydirectory',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.practice', verbose_name='Practice'),
        ),
    ]
