# Generated by Django 4.1.6 on 2023-05-25 11:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_creator_and_more"),
        ("taggit", "0005_auto_20220424_2025"),
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("policy_directory", "0010_alter_policydirectory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policydirectory",
            name="classification",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("promoção", "promoção"),
                    ("posicionamento", "posicionamento"),
                    ("mandato", "mandato"),
                    ("geral", "geral"),
                ],
                max_length=255,
                null=True,
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="policydirectory",
            name="description",
            field=models.TextField(
                max_length=1000, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="policydirectory",
            name="institutions",
            field=models.ManyToManyField(
                to="institution.institution", verbose_name="Instituição"
            ),
        ),
        migrations.AlterField(
            model_name="policydirectory",
            name="keywords",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Palavra-chave",
            ),
        ),
        migrations.AlterField(
            model_name="policydirectory",
            name="practice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="policydirectory",
            name="source",
            field=models.CharField(max_length=255, null=True, verbose_name="Origem"),
        ),
        migrations.AlterField(
            model_name="policydirectory",
            name="thematic_areas",
            field=models.ManyToManyField(
                to="usefulmodels.thematicarea", verbose_name="Área temática"
            ),
        ),
    ]
