# Generated by Django 3.2.12 on 2022-08-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_directory', '0012_policydirectory_record_status'),
        ('policy_directory', '0012_policydirectory_source'),
    ]

    operations = [
    ]
