# Generated by Django 3.2.12 on 2022-08-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('identifier', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('language', models.CharField(blank=True, choices=[('', ''), ('Pt', 'Pt'), ('Es', 'Es'), ('En', 'En')], max_length=5, null=True, verbose_name='Idioma')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.name')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
