# Generated by Django 3.2.12 on 2022-09-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_auto_20220826_1504'),
        ('location', '0002_remove_location_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usefulmodels', '0002_state_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('identifier', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifier')),
                ('generation_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Generation date')),
                ('generated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Generated by')),
                ('registered_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registered by')),
                ('record_status', models.CharField(blank=True, choices=[('', ''), ('WIP', 'WIP'), ('TO_MODERATE', 'TO_MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status')),
                ('availability_status', models.CharField(blank=True, choices=[('', ''), ('CURRENT', 'CURRENT'), ('DEACTIVATED', 'DEACTIVATED')], max_length=255, null=True, verbose_name='Availability status')),
                ('open_access', models.CharField(blank=True, choices=[('', ''), ('0', 'não'), ('1', 'sim'), ('2', 'ign'), ('3', 'all')], max_length=255, null=True, verbose_name='Open access')),
                ('qualifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualifier')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem')),
                ('action', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.action', verbose_name='Ação')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('geographic_context', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', verbose_name='Geographic context')),
                ('institutional_context', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institutional context')),
                ('practice', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.practice', verbose_name='Practice')),
                ('previous_record', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.indicator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
