# Generated by Django 3.2.12 on 2022-08-30 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('identifier', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('language', models.CharField(blank=True, choices=[('', ''), ('Pt', 'Pt'), ('Es', 'Es'), ('En', 'En')], max_length=5, null=True, verbose_name='Idioma')),
                ('date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Data')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='identity_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='name',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='indicator',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.identity'),
        ),
    ]
