# Generated by Django 3.2.12 on 2022-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20220830_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='identity',
            name='posterior_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Posterior Number'),
        ),
        migrations.AddField(
            model_name='identity',
            name='previous_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Previous Number'),
        ),
    ]
