# Generated by Django 3.2.12 on 2022-09-23 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0004_alter_country_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicator', '0002_auto_20220914_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('post_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Post Date')),
                ('authorship_post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authorship of the Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Versioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('record_status', models.CharField(blank=True, choices=[('', ''), ('WIP', 'WIP'), ('TO MODERATE', 'TO MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='generation_date',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='open_access',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='previous_record',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='qualifier',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='record_status',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='source',
        ),
        migrations.AddField(
            model_name='indicator',
            name='thematic_area',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.thematicarea', verbose_name='Área temática'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['name'], name='indicator_i_name_bf54a8_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['action'], name='indicator_i_action__8f231a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['practice'], name='indicator_i_practic_7b6df5_idx'),
        ),
        migrations.AddField(
            model_name='versioning',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='versioning_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='versioning',
            name='posterior_record',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_register', to='indicator.indicator', verbose_name='Posterior Record'),
        ),
        migrations.AddField(
            model_name='versioning',
            name='previous_record',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor_register', to='indicator.indicator', verbose_name='Previous Record'),
        ),
        migrations.AddField(
            model_name='versioning',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versioning_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='post',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='versioning',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.versioning', verbose_name='Versioning'),
        ),
    ]
