# Generated by Django 3.2.12 on 2022-08-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20220830_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='created',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='updated_by',
        ),
    ]
