# Generated by Django 3.2.12 on 2022-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicator", "0004_auto_20220923_2116"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="chronology",
            field=models.DateField(
                blank=True, max_length=255, null=True, verbose_name="Data"
            ),
        ),
    ]
