# Generated by Django 3.2.12 on 2022-08-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0014_auto_20220825_1530'),
        ('location', '0010_alter_location_options'),
        ('institution', '0004_institution_acronym'),
        ('indicator', '0004_auto_20220830_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='identity',
        ),
        migrations.AddField(
            model_name='indicator',
            name='action',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.action', verbose_name='Ação'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('', ''), ('CURRENT', 'CURRENT'), ('DEACTIVATED', 'DEACTIVATED')], max_length=255, null=True, verbose_name='Availability status'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='generated_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Generated by'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='generation_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Generation date'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='geographic_context',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', verbose_name='Geographic context'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='identifier',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='institutional_context',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institutional context'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='open_access',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'não'), ('1', 'sim'), ('2', 'ign'), ('3', 'all')], max_length=255, null=True, verbose_name='Open access'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='practice',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.practice', verbose_name='Practice'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='previous_record',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='qualifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualifier'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WIP'), ('TO_MODERATE', 'TO_MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='registered_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registered by'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem'),
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
