# Generated by Django 3.2.12 on 2022-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20220927_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='end_time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='Hora final'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='start_time',
            field=models.TimeField(blank=True, max_length=255, null=True, verbose_name='Hora inicial'),
        ),
    ]
