# Generated by Django 3.2.12 on 2022-09-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20220928_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='results',
        ),
        migrations.AddField(
            model_name='indicator',
            name='results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.results'),
        ),
    ]
