# Generated by Django 3.2.12 on 2022-11-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20221108_2356'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indicator',
            name='indicator_i_scienti_e668fa_idx',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='scientific_production',
        ),
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.CharField(max_length=255, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='context',
            field=models.CharField(max_length=255, null=True, verbose_name='Contexto'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='object_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['object_name'], name='indicator_i_object__785a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['category'], name='indicator_i_categor_111a26_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['context'], name='indicator_i_context_564325_idx'),
        ),
        migrations.DeleteModel(
            name='ScientificProduction',
        ),
    ]
