# Generated by Django 3.2.12 on 2022-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20220928_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioning',
            name='created',
        ),
        migrations.RemoveField(
            model_name='versioning',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='versioning',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='versioning',
            name='updated_by',
        ),
    ]
