# Generated by Django 4.1.6 on 2023-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0009_alter_indicator_creator_alter_indicator_updated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicator",
            options={"permissions": (("must_be_moderate", "Must be moderated"),)},
        ),
        migrations.AlterField(
            model_name="indicator",
            name="record_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("WIP", "WORK IN PROGRESS"),
                    ("TO MODERATE", "TO MODERATE"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("NOT PUBLISHED", "NOT PUBLISHED"),
                ],
                max_length=255,
                null=True,
                verbose_name="Record status",
            ),
        ),
    ]
