# Generated by Django 4.1.6 on 2023-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0011_alter_indicator_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
