# Generated by Django 4.1.6 on 2023-05-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0012_indicator_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="slug",
            field=models.SlugField(max_length=512, null=True, unique=True),
        ),
    ]
