# Generated by Django 4.1.6 on 2023-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0015_alter_indicator_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="link_to_data",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link to the data"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="link_to_graphic",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link to graphic"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="object_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Observation"
            ),
        ),
    ]
