# Generated by Django 4.1.6 on 2023-11-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0019_remove_indicator_indicator_i_descrip_361176_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                (
                    "raw_data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="JSONL Zip File",
                    ),
                ),
                (
                    "data_ids",
                    models.JSONField(blank=True, null=True, verbose_name="Data ids"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="raw_data",
        ),
        migrations.AddField(
            model_name="indicator",
            name="indicator_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicator.indicatorfile",
            ),
        ),
    ]
