# Generated by Django 4.1.6 on 2023-11-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0020_indicatorfile_remove_indicator_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorfile",
            name="name",
            field=models.CharField(max_length=1024, verbose_name="File name"),
        ),
    ]
