# Generated by Django 4.1.6 on 2024-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicator", "0022_remove_indicatorfile_data_ids_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicatorfile",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="indicatorfile",
            name="is_dynamic_data",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Dynamic Data"
            ),
        ),
    ]
