# Generated by Django 5.2.10 on 2026-02-24 15:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        help_text="Nome do índice no OpenSearch", max_length=255
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome de exibição para o usuário",
                        max_length=255,
                    ),
                ),
                (
                    "source_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de campos retornados do ES, ex: ['_id', 'title']",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
            },
        ),
        migrations.CreateModel(
            name="SettingsFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Chave do filtro, ex: 'document_type.keyword', 'publication_year'",
                        max_length=255,
                    ),
                ),
                (
                    "index_field_name",
                    models.CharField(
                        help_text="Campo no índice OpenSearch, ex: 'type.keyword', 'publication_year'",
                        max_length=255,
                    ),
                ),
                (
                    "field_autocomplete",
                    models.CharField(
                        blank=True,
                        help_text="Campo de autocomplete no OpenSearch, se houver",
                        max_length=255,
                    ),
                ),
                (
                    "filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuração do filtro: {size, order, transform}",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurações de UI: {class_filter, label, support_search_as_you_type, support_query_operator, category, display_transform, multiple_selection}",
                    ),
                ),
                (
                    "data_source",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_filters",
                        to="search_gateway.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings Filter",
                "verbose_name_plural": "Settings Filters",
                "unique_together": {("data_source", "field_name")},
            },
        ),
    ]
