# Generated by Django 5.2.10 on 2026-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="field_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuração completa dos filtros. Dict cujas chaves são field_name e valores contêm: index_field_name, field_autocomplete, filter, settings.",
            ),
        ),
        migrations.DeleteModel(
            name="SettingsFilter",
        ),
    ]
