# Generated by Django 5.2.10 on 2026-03-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_gateway", "0003_datasource_form_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="field_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuração completa dos filtros e formulários. Shape canônico: {fields: {...}, forms: {...}}.",
            ),
        ),
    ]
