# Generated by Django 5.2.10 on 2026-06-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_gateway", "0004_alter_datasource_field_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="metric_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuração de métricas dinâmicas. Shape canônico: {groups: {...}, displays: {...}}.",
            ),
        ),
    ]
