from django.utils.translation import gettext as _

thematic_level0 = (
    ('', ''),
    ('Ciências da Vida', _('Ciências da Vida')),
    ('Ciências Físicas, Tecnológicas e Multidisciplinares', _('Ciências Físicas, Tecnológicas e Multidisciplinares')),
    ('Humanidades', _('Humanidades')),
    ('ALL', _('ALL')),
    ('NOT_APPLICABLE', _('NOT_APPLICABLE')),
    ('UNDEFINED', _('UNDEFINED')),
)

thematic_level1 = (
    ('', ''),
    ('Ciências Agrárias', _('Ciências Agrárias')),
    ('Ciências Biológicas', _('Ciências Biológicas')),
    ('Ciências da Saúde', _('Ciências da Saúde')),
    ('Ciências Exatas e da Terra', _('Ciências Exatas e da Terra')),
    ('Ciências Humanas', _('Ciências Humanas')),
    ('Ciências Sociais Aplicadas', _('Ciências Sociais Aplicadas')),
    ('Engenharias', _('Engenharias')),
    ('Linguística, Letras e Artes', _('Linguística, Letras e Artes')),
    ('Multidisciplinar', _('Multidisciplinar')),
    ('ALL', _('ALL')),
    ('NOT_APPLICABLE', _('NOT_APPLICABLE')),
    ('UNDEFINED', _('UNDEFINED')),
)

thematic_level2 = (
    ('', ''),
    ('Ciências Agrárias I', _('Ciências Agrárias I')),
    ('Ciência de Alimentos', _('Ciência de Alimentos')),
    ('Medicina Veterinária – Memória de Documentos', _('Medicina Veterinária – Memória de Documentos')),
    ('Medicina Veterinária', _('Medicina Veterinária')),
    ('Zootecnia/Recursos Pesqueiros', _('Zootecnia/Recursos Pesqueiros')),
    ('Ciência de Alimentos – Memória de documentos', _('Ciência de Alimentos – Memória de documentos')),
    ('Biodiversidade', _('Biodiversidade')),
    ('Ciências Biológicas I', _('Ciências Biológicas I')),
    ('Ciências Biológicas II', _('Ciências Biológicas II')),
    ('Ciências Biológicas III', _('Ciências Biológicas III')),
    ('Biodiversidade – Memória da área', _('Biodiversidade – Memória da área')),
    ('Ciências Biológicas I – Memória da área', _('Ciências Biológicas I – Memória da área')),
    ('Ciências Biológicas II – Memória da área', _('Ciências Biológicas II – Memória da área')),
    ('Ciências Biológicas III – Memória da área', _('Ciências Biológicas III – Memória da área')),
    ('Educação Física', _('Educação Física')),
    ('Enfermagem', _('Enfermagem')),
    ('Farmácia', _('Farmácia')),
    ('Medicina I', _('Medicina I')),
    ('Medicina II', _('Medicina II')),
    ('Medicina III', _('Medicina III')),
    ('Nutrição', _('Nutrição')),
    ('Odontologia', _('Odontologia')),
    ('Saúde Coletiva', _('Saúde Coletiva')),
    ('Educação Física – Memória da área', _('Educação Física – Memória da área')),
    ('Enfermagem – Memória da área', _('Enfermagem – Memória da área')),
    ('Farmácia – Memória da área', _('Farmácia – Memória da área')),
    ('Medicina I – Memória da área', _('Medicina I – Memória da área')),
    ('Medicina II – Memória da área', _('Medicina II – Memória da área')),
    ('Medicina III – Memória da área', _('Medicina III – Memória da área')),
    ('Odontologia – Memória da área', _('Odontologia – Memória da área')),
    ('Saúde Coletiva – Memória da área', _('Saúde Coletiva – Memória da área')),
    ('Antropologia/Arqueologia', _('Antropologia/Arqueologia')),
    ('Ciência Política e Relações Internacionais', _('Ciência Política e Relações Internacionais')),
    ('Ciências da Religião e Teologia', _('Ciências da Religião e Teologia')),
    ('Educação', _('Educação')),
    ('Filosofia', _('Filosofia')),
    ('Geografia', _('Geografia')),
    ('História', _('História')),
    ('Psicologia', _('Psicologia')),
    ('Sociologia', _('Sociologia')),
    ('Antropologia/Arqueologia – Memória da área', _('Antropologia/Arqueologia – Memória da área')),
    ('Ciência Política e Relações Internacionais – Memória da área', _('Ciência Política e Relações Internacionais – Memória da área')),
    ('Ciências da Religião e Teologia – Memória da área', _('Ciências da Religião e Teologia – Memória da área')),
    ('Educação – Memória da área', _('Educação – Memória da área')),
    ('Filosofia – Memória da área', _('Filosofia – Memória da área')),
    ('Geografia – Memória da área', _('Geografia – Memória da área')),
    ('História – Memória da área', _('História – Memória da área')),
    ('Psicologia – Memória da área', _('Psicologia – Memória da área')),
    ('Sociologia – Memória da área', _('Sociologia – Memória da área')),
    ('Administração Pública e de Empresas, Ciências Contábeis e Turismo', _('Administração Pública e de Empresas, Ciências Contábeis e Turismo')),
    ('Arquitetura, Urbanismo e Design', _('Arquitetura, Urbanismo e Design')),
    ('Comunicação e Informação', _('Comunicação e Informação')),
    ('Direito', _('Direito')),
    ('Economia', _('Economia')),
    ('Planejamento Urbano e Regional/Demografia', _('Planejamento Urbano e Regional/Demografia')),
    ('Serviço Social', _('Serviço Social')),
    ('Administração Pública e de Empresas, Ciências Contábeis e Turismo - Memória da área', _('Administração Pública e de Empresas, Ciências Contábeis e Turismo - Memória da área')),
    ('Comunicação e Informação - Memória da área', _('Comunicação e Informação - Memória da área')),
    ('Direito - Memória da área ', _('Direito - Memória da área ')),
    ('Economia - Memória da área', _('Economia - Memória da área')),
    ('Planejamento Urbano e Reginal/Demografia - Memória da Área', _('Planejamento Urbano e Reginal/Demografia - Memória da Área')),
    ('Serviço Social - Memória da área', _('Serviço Social - Memória da área')),
    ('Artes', _('Artes')),
    ('Linguística e Literatura', _('Linguística e Literatura')),
    ('Artes - Memória de documentos', _('Artes - Memória de documentos')),
    ('Linguística e Literatura - Memória da área', _('Linguística e Literatura - Memória da área')),
    ('Astronomia/Física', _('Astronomia/Física')),
    ('Ciência da Computação', _('Ciência da Computação')),
    ('Geociências', _('Geociências')),
    ('Matemática/Probabilidade e Estatística', _('Matemática/Probabilidade e Estatística')),
    ('Química', _('Química')),
    ('Astronomia/Física - Memória da área', _('Astronomia/Física - Memória da área')),
    ('Ciência da Computação - Memória da área', _('Ciência da Computação - Memória da área')),
    ('Geociências - Memória da área ', _('Geociências - Memória da área ')),
    ('Matemática/Probabilidade e Estatística - Memória da área', _('Matemática/Probabilidade e Estatística - Memória da área')),
    ('Química - Memória da área', _('Química - Memória da área')),
    ('Engenharias I', _('Engenharias I')),
    ('Engenharias II', _('Engenharias II')),
    ('Engenharias III', _('Engenharias III')),
    ('Engenharias IV', _('Engenharias IV')),
    ('Engenharias I - Memória da área', _('Engenharias I - Memória da área')),
    ('Engenharias I - Memória da área', _('Engenharias I - Memória da área')),
    ('Engenharias III - Memória da área', _('Engenharias III - Memória da área')),
    ('Engenharias IV - Memória da área', _('Engenharias IV - Memória da área')),
    ('Biotecnologia', _('Biotecnologia')),
    ('Ciências Ambientais', _('Ciências Ambientais')),
    ('Ensino', _('Ensino')),
    ('Interdisciplinar', _('Interdisciplinar')),
    ('Materiais ', _('Materiais ')),
    ('Biotecnologia - Memória da área', _('Biotecnologia - Memória da área')),
    ('Ciências Ambientais - Memória da área', _('Ciências Ambientais - Memória da área')),
    ('Ensino - Memória da área', _('Ensino - Memória da área')),
    ('Interdisciplinar - Memória da área', _('Interdisciplinar - Memória da área')),
    ('Materiais - Memória da área', _('Materiais - Memória da área')),
    ('ALL', _('ALL')),
    ('NOT_APPLICABLE', _('NOT_APPLICABLE')),
    ('UNDEFINED', _('UNDEFINED')),
)

regions = (
    ('', ''),
    ('Norte', 'Norte'),
    ('Nordeste', 'Nordeste'),
    ('Centro-oeste', 'Centro-Oeste'),
    ('Sudeste', 'Sudeste'),
    ('Sul', 'Sul'),
    ('ALL', _('ALL')),
    ('NOT APPLICABLE', _('NOT_APPLICABLE')),
    ('UNDEFINED', _('UNDEFINED')),
)
