from django.utils.translation import gettext as _

thematic_level0 = (
    ('', ''),
    ('Ciências da Vida', _('Ciências da Vida')),
    ('Ciências Físicas, Tecnológicas e Multidisciplinares', _('Ciências Físicas, Tecnológicas e Multidisciplinares')),
    ('humanidades', _('Humanidades')),
)

thematic_level1 = (
    ('', ''),
    ('Ciências Agrárias', _('Ciências Agrárias')),
    ('Ciências Biológicas', _('Ciências Biológicas')),
    ('Ciências da Saúde', _('Ciências da Saúde')),
    ('Ciências Exatas e da Terra', _('Ciências Exatas e da Terra')),
    ('Ciências Humanas', _('Ciências Humanas')),
    ('Ciências Sociais Aplicadas', _('Ciências Sociais Aplicadas')),
    ('Engenharias', _('Engenharias')),
    ('Lingüística, Letras e Artes', _('Lingüística, Letras e Artes')),
)

thematic_level2 = (
    ('', ''),
    ('Ciência de Alimentos', _('Ciência de Alimentos')),
    ('Ciências Agrárias I', _('Ciências Agrárias I')),
    ('Medicina Veterinária', _('Medicina Veterinária')),
    ('Zootecnia/Recursos Pesqueiros', _('Zootecnia/Recursos Pesqueiros')),
    ('Biodiversidade', _('Biodiversidade')),
    ('Ciências Biológicas I', _('Ciências Biológicas I')),
    ('Ciências Biológicas II', _('Ciências Biológicas II')),
    ('Ciências Biológicas III', _('Ciências Biológicas III')),
    ('Educação Física', _('Educação Física')),
    ('Enfermagem', _('Enfermagem')),
    ('Farmácia', _('Farmácia')),
    ('Medicina I', _('Medicina I')),
    ('Medicina II', _('Medicina II')),
    ('Medicina III', _('Medicina III')),
    ('Nutrição', _('Nutrição')),
    ('Odontologia', _('Odontologia')),
    ('Saúde Coletiva', _('Saúde Coletiva')),
    ('Astronomia/Física', _('Astronomia/Física')),
    ('Ciências da Computação', _('Ciências da Computação')),
    ('Geociências', _('Geociências')),
    ('Matemática/Probabilidade Estatística', _('Matemática/Probabilidade Estatística')),
    ('Química', _('Química')),
    ('Antropologia/Arqueologia', _('Antropologia/Arqueologia')),
    ('Ciência Política e Relações Internacionais', _('Ciência Política e Relações Internacionais')),
    ('Ciências da Religião e Teologia', _('Ciências da Religião e Teologia')),
    ('Educação', _('Educação')),
    ('Filosofia', _('Filosofia')),
    ('Geografia', _('Geografia')),
    ('História', _('História')),
    ('Psicologia', _('Psicologia')),
    ('Sociologia', _('Sociologia')),
    ('Turismo', _('Turismo')),
    ('Arquitetura, Urbanismo e Design', _('Arquitetura, Urbanismo e Design')),
    ('Comunicação e Informação', _('Comunicação e Informação')),
    ('Direito', _('Direito')),
    ('Economia', _('Economia')),
    ('Planejamento Urbano e Regional/Demografia', _('Planejamento Urbano e Regional/Demografia')),
    ('Serviço Social', _('Serviço Social')),
    ('Engenharias', _('Engenharias')),
    ('Engenharias I', _('Engenharias I')),
    ('Engenharias II', _('Engenharias II')),
    ('Engenharias III', _('Engenharias III')),
    ('Engenharias IV', _('Engenharias IV')),
    ('Artes', _('Artes')),
    ('Linguística e Literatura', _('Linguística e Literatura')),
)
