# Generated by Django 3.2.12 on 2022-08-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0010_alter_location_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('institution', '0003_institution_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDirectoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('is_valid', models.BooleanField(blank=True, default=False, null=True, verbose_name='É válido')),
                ('line_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de linhas')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Anexo')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='eventdirectoryfile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventdirectoryfile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name_plural': 'EventDirectory Directory Upload',
            },
        ),
        migrations.CreateModel(
            name='EventDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('event', models.CharField(max_length=255, verbose_name='Evento')),
                ('link', models.URLField(verbose_name='Link')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('organization', models.TextField(max_length=255, verbose_name='Organização')),
                ('start_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='Data de fim')),
                ('start_time', models.TimeField(blank=True, max_length=255, null=True, verbose_name='Hora inicial')),
                ('end_time', models.TimeField(blank=True, max_length=255, null=True, verbose_name='Hora final')),
                ('is_online', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='eventdirectory_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('institutions', models.ManyToManyField(blank=True, to='institution.Institution')),
                ('locations', models.ManyToManyField(blank=True, to='location.Location')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventdirectory_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name_plural': 'EventDirectory Directory',
            },
        ),
    ]
