# Generated by Django 3.2.12 on 2022-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_institution_institution_type'),
        ('event_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdirectory',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='eventdirectory',
            name='organization',
            field=models.ManyToManyField(blank=True, to='institution.Institution', verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='eventdirectory',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WORK IN PROGRESS'), ('TO MODERATE', 'TO MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
    ]
