# Generated by Django 3.2.12 on 2022-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdirectory',
            name='is_online',
        ),
        migrations.AddField(
            model_name='eventdirectory',
            name='attendence',
            field=models.CharField(blank=True, choices=[('', ''), ('live', 'Live'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=255, null=True, verbose_name='Região'),
        ),
    ]
