# Generated by Django 3.2.12 on 2022-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0002_auto_20220816_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdirectory',
            name='attendence',
            field=models.CharField(blank=True, choices=[('', ''), ('live', 'Live'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=255, null=True, verbose_name='Attendence'),
        ),
    ]
