# Generated by Django 3.2.12 on 2023-02-15 18:43

from django.db import migrations, models
import django.db.models.deletion
import event_directory.models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0011_auto_20221108_2356'),
        ('event_directory', '0003_alter_eventdirectory_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdirectory',
            name='action',
            field=models.ForeignKey(blank=True, default=event_directory.models.get_default_action, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.action', verbose_name='Ação'),
        ),
    ]
