# Generated by Django 3.2.12 on 2022-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_institution_institution_type'),
        ('event_directory', '0003_alter_eventdirectory_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdirectory',
            name='organization',
        ),
        migrations.AddField(
            model_name='eventdirectory',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='institution.Institution', verbose_name='Instituição'),
        ),
    ]
