# Generated by Django 4.1.6 on 2023-04-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_directory", "0005_alter_eventdirectory_creator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventdirectory",
            options={
                "permissions": (("must_be_moderate", "Must be moderated"),),
                "verbose_name_plural": "EventDirectory Directory",
            },
        ),
    ]
