# Generated by Django 3.2.12 on 2022-10-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0005_alter_eventdirectory_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdirectory',
            name='institutions',
        ),
    ]
