# Generated by Django 3.2.12 on 2022-08-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0009_alter_eventdirectory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdirectory',
            name='pratice',
        ),
    ]
