# Generated by Django 4.1.6 on 2023-05-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_alter_location_creator_alter_location_updated_by"),
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("taggit", "0005_auto_20220424_2025"),
        ("event_directory", "0009_alter_eventdirectory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventdirectory",
            options={
                "permissions": (
                    ("must_be_moderate", "Must be moderated"),
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_link", "Can edit link"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_locations", "Can edit locations"),
                    ("can_edit_institutions", "Can edit institutions"),
                    ("can_edit_thematic_areas", "Can edit thematic_areas"),
                    ("can_edit_practice", "Can edit practice"),
                    ("can_edit_action", "Can edit action"),
                    ("can_edit_classification", "Can edit classification"),
                    ("can_edit_keywords", "Can edit keywords"),
                    ("can_edit_attendance", "Can edit attendance"),
                    ("can_edit_record_status", "Can edit record_status"),
                    ("can_edit_source", "Can edit source"),
                    (
                        "can_edit_institutional_contribution",
                        "Can edit institutional_contribution",
                    ),
                    ("can_edit_notes", "Can edit notes"),
                ),
                "verbose_name": "Dissemination Data",
                "verbose_name_plural": "Dissemination Data",
            },
        ),
        migrations.AlterModelOptions(
            name="eventdirectoryfile",
            options={"verbose_name_plural": "Dissemination Data Upload"},
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("live", "Presencial"),
                    ("virtual", "Remoto"),
                    ("hybrid", "Híbrido"),
                ],
                max_length=255,
                null=True,
                verbose_name="Attendance",
            ),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="classification",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("encontro", "encontro"),
                    ("conferência", "conferência"),
                    ("congresso", "congresso"),
                    ("workshop", "workshop"),
                    ("seminário", "seminário"),
                    ("outros", "outros"),
                ],
                max_length=255,
                null=True,
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="description",
            field=models.TextField(
                max_length=1000, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="keywords",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Palavra-chave",
            ),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="locations",
            field=models.ManyToManyField(
                to="location.location", verbose_name="Localização"
            ),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="practice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="source",
            field=models.CharField(max_length=255, null=True, verbose_name="Origem"),
        ),
        migrations.AlterField(
            model_name="eventdirectory",
            name="thematic_areas",
            field=models.ManyToManyField(
                to="usefulmodels.thematicarea", verbose_name="Área temática"
            ),
        ),
    ]
