# Generated by Django 3.2.12 on 2022-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0011_eventdirectory_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdirectory',
            name='event',
        ),
        migrations.AddField(
            model_name='eventdirectory',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
