# Generated by Django 3.2.12 on 2022-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0013_auto_20220826_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdirectory',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem'),
        ),
    ]
