# Generated by Django 3.2.12 on 2022-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0013_eventdirectory_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdirectory',
            name='attendence',
            field=models.CharField(blank=True, choices=[('', ''), ('live', 'Presencial'), ('virtual', 'Remoto'), ('hybrid', 'Híbrido')], max_length=255, null=True, verbose_name='Presença'),
        ),
    ]
