# Generated by Django 3.2.12 on 2022-08-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0013_eventdirectory_record_status'),
        ('event_directory', '0014_eventdirectory_source'),
    ]

    operations = [
    ]
