# Generated by Django 3.2.12 on 2022-08-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0015_merge_20220826_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdirectory',
            name='attendence',
        ),
        migrations.AddField(
            model_name='eventdirectory',
            name='attendance',
            field=models.CharField(blank=True, choices=[('', ''), ('live', 'Live'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=255, null=True, verbose_name='Attendance'),
        ),
    ]
