# Generated by Django 4.1.6 on 2025-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Rótulo")),
                ("scope", models.CharField(max_length=255, verbose_name="Escopo")),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("iframe", "Iframe"), ("image", "Imagem")],
                        max_length=10,
                        verbose_name="Tipo de Gráfico",
                    ),
                ),
                (
                    "iframe_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL do iframe"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="charts/images/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "data_zip",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="charts/zips/",
                        verbose_name="Arquivo ZIP com dados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gráfico",
                "verbose_name_plural": "Gráficos",
            },
        ),
    ]
