# Generated by Django 4.1.6 on 2025-07-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="title",
            field=models.CharField(default=None, max_length=255, verbose_name="Título"),
            preserve_default=False,
        ),
    ]
