# Generated by Django 4.1.6 on 2025-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0002_chart_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="label",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Rótulo"
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="scope",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Escopo"
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Título"
            ),
        ),
    ]
