# Generated by Django 4.1.6 on 2025-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0003_alter_chart_label_alter_chart_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="iframe_url",
            field=models.TextField(blank=True, null=True, verbose_name="URL do iframe"),
        ),
    ]
