# Generated by Django 4.1.6 on 2025-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0004_alter_chart_iframe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="link_chart",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Link"
            ),
        ),
    ]
