# Generated by Django 3.2.12 on 2022-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_location_options'),
        ('education_directory', '0002_auto_20220809_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdirectory',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='location.Location'),
        ),
    ]
