# Generated by Django 3.2.12 on 2022-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_institution_type'),
        ('location', '0010_alter_location_options'),
        ('education_directory', '0003_educationdirectory_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdirectory',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='institution.Institution'),
        ),
        migrations.AlterField(
            model_name='educationdirectory',
            name='locations',
            field=models.ManyToManyField(blank=True, to='location.Location'),
        ),
    ]
