# Generated by Django 4.1.6 on 2023-04-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education_directory", "0004_alter_educationdirectory_creator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationdirectory",
            options={
                "permissions": (("must_be_moderate", "Must be moderated"),),
                "verbose_name_plural": "Diretório de Educação",
            },
        ),
    ]
