# Generated by Django 3.2.12 on 2022-08-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_directory', '0004_auto_20220815_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdirectory',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
