# Generated by Django 3.2.12 on 2022-08-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_directory', '0005_educationdirectory_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdirectory',
            name='institution',
        ),
    ]
