# Generated by Django 3.2.12 on 2022-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulmodels', '0008_alter_thematicarea_options'),
        ('education_directory', '0006_remove_educationdirectory_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdirectory',
            name='thematic_areas',
            field=models.ManyToManyField(blank=True, to='usefulmodels.ThematicArea'),
        ),
    ]
