# Generated by Django 4.1.6 on 2023-05-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_directory", "0006_alter_educationdirectory_record_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationdirectory",
            name="institutional_contribution",
            field=models.CharField(
                default="SciELO",
                help_text="Name of the contributing institution, default=SciELO.",
                max_length=255,
                verbose_name="Institutional Contribution",
            ),
        ),
        migrations.AddField(
            model_name="educationdirectory",
            name="notes",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Notes"
            ),
        ),
    ]
