# Generated by Django 4.1.6 on 2023-05-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "education_directory",
            "0007_educationdirectory_institutional_contribution_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationdirectory",
            options={
                "permissions": (
                    ("must_be_moderate", "Must be moderated"),
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_link", "Can edit link"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_start_date", "Can edit start_date"),
                    ("can_edit_end_date", "Can edit end_date"),
                    ("can_edit_start_time", "Can edit start_time"),
                    ("can_edit_end_time", "Can edit end_time"),
                    ("can_edit_locations", "Can edit locations"),
                    ("can_edit_institutions", "Can edit institutions"),
                    ("can_edit_thematic_areas", "Can edit thematic_areas"),
                    ("can_edit_practice", "Can edit practice"),
                    ("can_edit_action", "Can edit action"),
                    ("can_edit_classification", "Can edit classification"),
                    ("can_edit_keywords", "Can edit keywords"),
                    ("can_edit_attendance", "Can edit attendance"),
                    ("can_edit_record_status", "Can edit record_status"),
                    ("can_edit_source", "Can edit source"),
                    (
                        "can_edit_institutional_contribution",
                        "Can edit institutional_contribution",
                    ),
                    ("can_edit_notes", "Can edit notes"),
                ),
                "verbose_name_plural": "Diretório de Educação",
            },
        ),
    ]
