# Generated by Django 4.1.6 on 2023-07-16 21:03

from django.db import migrations, models
import django.db.models.deletion
import education_directory.models


class Migration(migrations.Migration):

    dependencies = [
        ("usefulmodels", "0012_alter_action_creator_alter_action_updated_by_and_more"),
        ("education_directory", "0013_alter_educationdirectory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationdirectory",
            name="action",
            field=models.ForeignKey(
                blank=True,
                default=education_directory.models.get_default_action,
                help_text="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.action",
                verbose_name="Ação",
            ),
        ),
    ]
