# Generated by Django 3.2.12 on 2022-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_directory', '0014_educationdirectory_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdirectory',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WIP'), ('TO_MODERATE', 'TO_MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
    ]
