# Generated by Django 3.2.12 on 2022-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_directory', '0015_educationdirectory_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdirectory',
            name='is_online',
        ),
        migrations.AddField(
            model_name='educationdirectory',
            name='attendance',
            field=models.CharField(blank=True, choices=[('', ''), ('live', 'Presencial'), ('virtual', 'Remoto'), ('hybrid', 'Híbrido')], max_length=255, null=True, verbose_name='Attendance'),
        ),
    ]
