# Generated by Django 4.1.6 on 2026-01-27 09:35

from django.db import migrations, models
import django.db.models.deletion
import education_directory.models


class Migration(migrations.Migration):

    dependencies = [
        ("usefulmodels", "0013_alter_practice_options_and_more"),
        ("education_directory", "0015_alter_educationdirectory_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationdirectory",
            options={
                "permissions": (
                    ("must_be_moderate", "Must be moderated"),
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_link", "Can edit link"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_start_date", "Can edit start_date"),
                    ("can_edit_end_date", "Can edit end_date"),
                    ("can_edit_start_time", "Can edit start_time"),
                    ("can_edit_end_time", "Can edit end_time"),
                    ("can_edit_locations", "Can edit locations"),
                    ("can_edit_institutions", "Can edit institutions"),
                    ("can_edit_thematic_areas", "Can edit thematic_areas"),
                    ("can_edit_practice", "Can edit practice"),
                    ("can_edit_classification", "Can edit classification"),
                    ("can_edit_keywords", "Can edit keywords"),
                    ("can_edit_attendance", "Presença"),
                    ("can_edit_record_status", "Can edit record_status"),
                    ("can_edit_source", "Can edit source"),
                    (
                        "can_edit_institutional_contribution",
                        "Can edit institutional_contribution",
                    ),
                    ("can_edit_notes", "Can edit notes"),
                ),
                "verbose_name": "Educação - Diretório",
                "verbose_name_plural": "Educação - Diretório",
            },
        ),
        migrations.AlterModelOptions(
            name="educationdirectoryfile",
            options={"verbose_name_plural": "Educação - Diretório Upload"},
        ),
        migrations.AddField(
            model_name="educationdirectory",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("gratuito", "Gratuito"), ("pago", "Pago")],
                help_text='Indique a disponibilidade: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#institui%C3%A7%C3%A3o-contribuidora" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#disponibilidade</a>',
                max_length=255,
                null=True,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="educationdirectory",
            name="action",
            field=models.ForeignKey(
                blank=True,
                default=education_directory.models.get_default_action,
                help_text="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.action",
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="educationdirectory",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("live", "Presencial"),
                    ("virtual", "Remoto"),
                    ("hybrid", "Híbrido"),
                ],
                max_length=255,
                null=True,
                verbose_name="Presença",
            ),
        ),
        migrations.AlterField(
            model_name="educationdirectory",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text='Anotações sobre o registro. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#notes" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#notes</a>',
                max_length=1000,
                null=True,
                verbose_name="Notas",
            ),
        ),
        migrations.AlterField(
            model_name="educationdirectory",
            name="practice",
            field=models.ForeignKey(
                help_text='Prática da ciência aberta referente ao item registrado. Veja exemplo em: <a href="https://github.com/scieloorg/scms-oca/wiki/Campos#pr%C3%A1tica" target="_blank">https://github.com/scieloorg/scms-oca/wiki/Campos#pr%C3%A1tica</a>',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usefulmodels.practice",
                verbose_name="Prática",
            ),
        ),
    ]
