# Generated by Django 3.2.12 on 2022-08-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_directory', '0015_educationdirectory_record_status'),
        ('education_directory', '0015_educationdirectory_source'),
    ]

    operations = [
    ]
