# Generated by Django 4.1.6 on 2026-01-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseHarvestErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Nome do campo que causou o erro, se aplicável",
                        max_length=100,
                        null=True,
                        verbose_name="Campo com Erro",
                    ),
                ),
                (
                    "exception_type",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Type"
                    ),
                ),
                (
                    "exception_message",
                    models.TextField(
                        help_text="Descrição detalhada do erro",
                        verbose_name="Mensagem de Erro",
                    ),
                ),
                (
                    "exception_traceback",
                    models.TextField(
                        blank=True,
                        help_text="Stack trace completo do erro (para debugging)",
                        null=True,
                        verbose_name="Traceback do Erro",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica se o erro foi resolvido",
                        verbose_name="Erro Resolvido",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações adicionais sobre o contexto do erro",
                        verbose_name="Dados de Contexto",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o erro foi resolvido",
                        null=True,
                        verbose_name="Resolvido em",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HarvestedSciELOData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do registro no sistema externo",
                        max_length=255,
                        unique=True,
                        verbose_name="ID Externo",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="URL da Fonte"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados completos retornados pelo endpoint",
                        verbose_name="Dados Brutos",
                    ),
                ),
                (
                    "harvest_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Coleta",
                    ),
                ),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Indexação",
                    ),
                ),
                (
                    "datestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do registro"
                    ),
                ),
                (
                    "last_harvest_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Tentativa de Coleta"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Indexado em"
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do índice no OpenSearch onde foi indexado",
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Índice",
                    ),
                ),
                (
                    "type_data",
                    models.CharField(
                        blank=True,
                        help_text="dataset ou dataverse",
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de dado",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados de Scielo Data",
                "verbose_name_plural": "Dados de Scielo",
            },
        ),
        migrations.CreateModel(
            name="HarvestedPreprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do registro no sistema externo",
                        max_length=255,
                        unique=True,
                        verbose_name="ID Externo",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="URL da Fonte"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados completos retornados pelo endpoint",
                        verbose_name="Dados Brutos",
                    ),
                ),
                (
                    "harvest_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Coleta",
                    ),
                ),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Indexação",
                    ),
                ),
                (
                    "datestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do registro"
                    ),
                ),
                (
                    "last_harvest_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Tentativa de Coleta"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Indexado em"
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do índice no OpenSearch onde foi indexado",
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Índice",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados de preprint puro",
                "verbose_name_plural": "Dados de preprint",
            },
        ),
        migrations.CreateModel(
            name="HarvestedBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do registro no sistema externo",
                        max_length=255,
                        unique=True,
                        verbose_name="ID Externo",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="URL da Fonte"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados completos retornados pelo endpoint",
                        verbose_name="Dados Brutos",
                    ),
                ),
                (
                    "harvest_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Coleta",
                    ),
                ),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Indexação",
                    ),
                ),
                (
                    "datestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do registro"
                    ),
                ),
                (
                    "last_harvest_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Tentativa de Coleta"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Indexado em"
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do índice no OpenSearch onde foi indexado",
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Índice",
                    ),
                ),
                (
                    "type_data",
                    models.CharField(
                        blank=True,
                        help_text="Part ou Monograph",
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de data",
                    ),
                ),
                (
                    "last_seq",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Sequência do _changes processada para este registro",
                        null=True,
                        verbose_name="Última sequência",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monograph relacionado quando o tipo for Part",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parts",
                        to="harvest.harvestedbooks",
                        verbose_name="Monograph",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados de Scielo Books",
                "verbose_name_plural": "Dados de Scielo Books",
            },
        ),
        migrations.CreateModel(
            name="HarvestErrorLogSciELOData",
            fields=[
                (
                    "baseharvesterrorlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="harvest.baseharvesterrorlog",
                    ),
                ),
                (
                    "scielo_data",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_error_log",
                        to="harvest.harvestedscielodata",
                    ),
                ),
            ],
            bases=("harvest.baseharvesterrorlog",),
        ),
        migrations.CreateModel(
            name="HarvestErrorLogPreprint",
            fields=[
                (
                    "baseharvesterrorlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="harvest.baseharvesterrorlog",
                    ),
                ),
                (
                    "preprint",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_error_log",
                        to="harvest.harvestedpreprint",
                    ),
                ),
            ],
            bases=("harvest.baseharvesterrorlog",),
        ),
        migrations.CreateModel(
            name="HarvestErrorLogBooks",
            fields=[
                (
                    "baseharvesterrorlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="harvest.baseharvesterrorlog",
                    ),
                ),
                (
                    "book",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_error_log",
                        to="harvest.harvestedbooks",
                    ),
                ),
            ],
            bases=("harvest.baseharvesterrorlog",),
        ),
    ]
