# Generated by Django 4.1.6 on 2026-02-13 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("harvest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseharvesterrorlog",
            name="occurrence_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de ocorrência"
            ),
        ),
        migrations.AlterField(
            model_name="harvestedbooks",
            name="datestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do registro"
            ),
        ),
        migrations.AlterField(
            model_name="harvestedpreprint",
            name="datestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do registro"
            ),
        ),
        migrations.AlterField(
            model_name="harvestedscielodata",
            name="datestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do registro"
            ),
        ),
        migrations.CreateModel(
            name="TransformationScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome identificador do script de transformação",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do que este script faz",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "source_index",
                    models.CharField(
                        help_text="Nome do índice OpenSearch de origem (ex: raw_scielo_book)",
                        max_length=100,
                        verbose_name="Índice de Origem",
                    ),
                ),
                (
                    "dest_index",
                    models.CharField(
                        help_text="Nome do índice OpenSearch de destino (ex: bronze_scielo_books)",
                        max_length=100,
                        verbose_name="Índice de Destino",
                    ),
                ),
                (
                    "query_script",
                    models.TextField(
                        blank=True,
                        help_text="Query JSON para selecionar documentos. Use {{identifier}} como placeholder para o ID do documento.",
                        null=True,
                        verbose_name="Query JSON",
                    ),
                ),
                (
                    "transform_script",
                    models.TextField(
                        help_text="Script Painless para transformação dos dados. Acesse os dados brutos via ctx._source.raw_data",
                        verbose_name="Script Painless",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Se desativado, a transformação não será executada",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "harvest_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HarvestedPreprint", "Preprint"),
                            ("HarvestedBooks", "Books"),
                            ("HarvestedSciELOData_dataset", "SciELO Data - Dataset"),
                            (
                                "HarvestedSciELOData_dataverse",
                                "SciELO Data - Dataverse",
                            ),
                        ],
                        db_index=True,
                        help_text="Modelo de coleta associado a este script para transformação automática",
                        max_length=50,
                        null=True,
                        verbose_name="Modelo de Coleta",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Script de Transformação",
                "verbose_name_plural": "Scripts de Transformação",
            },
        ),
    ]
