# Generated by Django 5.2.10 on 2026-05-20 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvest", "0002_baseharvesterrorlog_occurrence_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMetricsUploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo CSV ou XLSX com dados de métricas globais.",
                        upload_to="global_metrics_uploads/%Y/%m/%d/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Indica se o arquivo já foi processado com sucesso.",
                        verbose_name="Processado",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de métricas globais",
                "verbose_name_plural": "Arquivos de métricas globais",
            },
        ),
    ]
