# Generated by Django 5.2.10 on 2026-03-30 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search_gateway", "0004_alter_datasource_field_settings"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fonte de dados OpenSearch associada a esta página de busca.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observation_pages",
                        to="search_gateway.datasource",
                        verbose_name="Data Source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
