# Generated by Django 3.2.12 on 2022-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('', ''), ('agência de apoio à pesquisa', 'agência de apoio à pesquisa'), ('universidade e instâncias ligadas à universidades', 'universidade e instâncias ligadas à universidades'), ('empresa ou instituto ligadas ao governo', 'empresa ou instituto ligadas ao governo'), ('organização privada', 'organização privada'), ('organização sem fins de lucros', 'organização sem fins de lucros'), ('sociedade científica, associação pós-graduação, associação profissional', 'sociedade científica, associação pós-graduação, associação profissional'), ('outros', 'outros')], max_length=255, null=True, verbose_name='Institution Type'),
        ),
    ]
