# Generated by Django 3.2.12 on 2022-08-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_location_options'),
        ('institution', '0002_institution_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
