# Generated by Django 3.2.12 on 2022-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_institution_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acronym to the institution'),
        ),
    ]
