# Generated by Django 4.1.6 on 2023-07-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("institution", "0005_alter_institution_creator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specific_id",
                    models.CharField(max_length=255, verbose_name="Specific Id"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Source updated date"
                    ),
                ),
                (
                    "created",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Source created date"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON Data institution"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.source",
                        verbose_name="Origem",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="institutionsource",
            index=models.Index(
                fields=["specific_id"], name="institution_specifi_88a024_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionsource",
            index=models.Index(
                fields=["display_name"], name="institution_display_0ff556_idx"
            ),
        ),
    ]
