# Generated by Django 4.1.6 on 2023-07-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("institution", "0007_institutionsource_country_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstitutionSource",
            new_name="SourceInstitution",
        ),
        migrations.RenameIndex(
            model_name="sourceinstitution",
            new_name="institution_specifi_272b7e_idx",
            old_name="institution_specifi_88a024_idx",
        ),
        migrations.RenameIndex(
            model_name="sourceinstitution",
            new_name="institution_display_df2ea0_idx",
            old_name="institution_display_0ff556_idx",
        ),
    ]
