# Generated by Django 4.1.6 on 2023-10-15 14:26

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0010_institutiontranslatename"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutiontranslatename",
            name="source_institution",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_institution",
                to="institution.sourceinstitution",
            ),
        ),
    ]
