# Generated by Django 4.1.6 on 2023-10-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0010_institution_sources"),
        ("institution", "0011_institutiontranslatename_source_institution"),
    ]

    operations = []
