# Generated by Django 3.2.12 on 2022-10-13 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usefulmodels', '0004_alter_country_options'),
        ('institution', '0003_alter_institution_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaredNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=510, null=True, verbose_name='Declared Names')),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_issn_l', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISSN-L')),
                ('journal_issns', models.CharField(blank=True, max_length=50, null=True, verbose_name="ISSN's")),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do periódico')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publicador')),
                ('journal_is_in_doaj', models.BooleanField(blank=True, default=False, null=True, verbose_name='DOAJ')),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('given', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome dado')),
                ('orcid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID')),
                ('authenticated_orcid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Autenticado')),
                ('affiliation', models.ForeignKey(blank=True, max_length=510, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles_directory.affiliations')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Título')),
                ('volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Volume')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano')),
                ('open_access_status', models.CharField(blank=True, choices=[('', ''), ('gold', 'Gold'), ('hybrid', 'Hybrid'), ('bronze', 'Bronze'), ('green', 'Green'), ('closed', 'Closed')], max_length=50, null=True, verbose_name='Open Access Status')),
                ('use_license', models.CharField(blank=True, choices=[('', ''), ('CC0', 'CC0'), ('CC-BY', 'CC-BY'), ('CC-BYNC', 'CC-BYNC'), ('CC-BYND', 'CC-BYND'), ('CC-BYNCND', 'CC-BYNCND')], max_length=50, null=True, verbose_name='Use License')),
                ('apc', models.CharField(blank=True, choices=[('', ''), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True, verbose_name='Article Processing Charge')),
                ('source', models.CharField(blank=True, choices=[('', ''), ('UNPAYWALL', 'UNPAYWALL'), ('OTHERS', 'OTHERS')], max_length=50, null=True, verbose_name='Record Source')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.action', verbose_name='Ação')),
                ('contributors', models.ManyToManyField(blank=True, to='articles_directory.Contributors', verbose_name='Contribuidores')),
                ('journal', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles_directory.journals', verbose_name='Periódico')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usefulmodels.practice', verbose_name='Practice')),
                ('thematic_areas', models.ManyToManyField(blank=True, to='usefulmodels.ThematicArea', verbose_name='Área temática')),
            ],
        ),
        migrations.AddField(
            model_name='affiliations',
            name='names',
            field=models.ManyToManyField(blank=True, to='articles_directory.DeclaredNames', verbose_name='Affiliation Declared Names'),
        ),
        migrations.AddField(
            model_name='affiliations',
            name='official',
            field=models.ForeignKey(blank=True, max_length=1020, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_name', to='institution.institution', verbose_name='Official Affiliation Name'),
        ),
    ]
