# Generated by Django 3.2.12 on 2022-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['doi'], name='articles_di_doi_1f8bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='contributors',
            index=models.Index(fields=['orcid'], name='articles_di_orcid_bbe89e_idx'),
        ),
        migrations.AddIndex(
            model_name='journals',
            index=models.Index(fields=['journal_issn_l'], name='articles_di_journal_3e04d6_idx'),
        ),
    ]
