# Generated by Django 3.2.12 on 2022-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_institution_type'),
        ('location', '0010_alter_location_options'),
        ('disclosure_directory', '0003_auto_20220809_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuredirectory',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='disclosuredirectory',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disclosuredirectory',
            name='locations',
            field=models.ManyToManyField(blank=True, to='location.Location'),
        ),
    ]
