# Generated by Django 5.2.10 on 2026-04-14 16:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_formfield_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="embed",
            field=models.TextField(
                blank=True,
                help_text="Embed content for the page, such as an iframe or other embed code.",
                null=True,
                verbose_name="Embed",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="use_only_embed",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the page will only display the embed content without the body text.",
                verbose_name="Set only embed",
            ),
        ),
    ]
