# Generated by Django 4.1.6 on 2025-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freepage",
            name="embed_dash",
            field=models.TextField(
                blank=True,
                help_text="Embed content for the page, such as an iframe or other embed code.",
                null=True,
                verbose_name="Embed",
            ),
        ),
        migrations.AddField(
            model_name="freepage",
            name="use_only_embed",
            field=models.BooleanField(
                default=True,
                help_text="If checked, the page will only display the embed content without the body text.",
                verbose_name="Set only embed",
            ),
        ),
    ]
