# Generated by Django 4.1.6 on 2025-06-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freepage", "0002_freepage_embed_dash_freepage_use_only_embed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freepage",
            old_name="embed_dash",
            new_name="embed",
        ),
    ]
